### ISSUE TITLE
unable to register

### ISSUE THREAD

**Issue by h4wkmoon** [MycroftAI/mycroft-core#471] opened 2017-01-21 19:56 UTC
Hi, 
I've just installed successfully mycroft with dev_setup.sh
mycroft asks me to register to home.mycroft.ai.
But, the add_device web page does not react when I type my id in the input box.

Javascript error : 
`The page at 'https://home.mycroft.ai/#/device/add?_k=ri6gbz' was loaded over HTTPS, but requested an insecure resource 'http://localhost:8888/'. This request has been blocked; the content must be served over HTTPS.`

**Comment by aatchison** [comment] 2017-02-09 20:22
We have added a few fixes to the web client, are you able to register now?

**Comment by pickeld** [comment] 2017-03-16 21:02
same problem here. unable to register. problem persists

**Comment by aatchison** [comment] 2017-03-16 21:06
Hmm. I just checked to make sure that it's working. Can you be more specific? Is it the site or Mycroft itself? Do you have any logs? Also, what method did you use to get set up?

**Comment by pickeld** [comment] 2017-03-16 21:19
hey there. 
when trying to sign up using the form on https://home.mycroft.ai (facebook/github/google). it opens a window where it says " waiting for api.mycroft.ai..." eventually i get a msg on screen saying 
```
The server was not able to produce a timely response to your request.
Please try again in a short while!
```

**Comment by aatchison** [comment] 2017-03-16 21:26
hmm.
I just used all three and created an account also. Looking into it.
What browser are you using?

**Comment by pickeld** [comment] 2017-03-16 21:27
tried ff and chrome. latest version. let me dive deep and wireshark

**Comment by aatchison** [comment] 2017-03-16 21:27
Okay, thanks!

**Comment by pickeld** [comment] 2017-03-16 21:35
no hint using wireshark. i just get a timeout from api.mycroft.ai [162.243.58.111] [fin ack]...

**Comment by aatchison** [comment] 2017-03-16 21:36
We seem to be having some database issues here actually.

**Comment by pickeld** [comment] 2017-03-16 21:37
keep on doing incredible things. please if you can. let me know when you back on track
good luck!

**Comment by aatchison** [comment] 2017-03-16 21:39
Thanks :) Mind trying one more time?

**Comment by pickeld** [comment] 2017-03-16 21:41
yay! problem fixed! thank you!

**Comment by aatchison** [comment] 2017-03-16 21:41
No problem:)

**Comment by AsavarTzeth** [comment] 2017-03-23 09:50
I have the exact same issue. I used to be able to login to cerberus.mycroft.ai with Google. I gather home.mycroft.ai is the replacement?

Info:
I get the exact same javascript console output.

Chrome won't allow unencrypted connections to localhost if the the current site is loaded over https. I bypass this by allowing insecure scripts (since localhost is safe). However it still fails.

I ran netstat to see if anything listens on localhost:8888. There I find mycroft listens to 0.0.0.0:8181 by default. If this is the service home.mycroft.ai expects the port is wrong. I think I fixed this by going into mycroft/configuration/mycroft.conf and changing websocket.port to 8888. But now I get this:

```
Fetch API cannot load http://localhost:8888/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://home.mycroft.ai' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
/#/login?_k=9al4d9:1 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by augustnmonteiro** [comment] 2017-04-24 21:43
Hi @AsavarTzeth you still having this problem?

**Comment by AsavarTzeth** [comment] 2017-04-25 14:46
I just tried v0.8.10 and yes the issue is very much still present.

**Comment by augustnmonteiro** [comment] 2017-06-26 18:51
Hi @AsavarTzeth, do you still having this issue?

**Comment by AsavarTzeth** [comment] 2017-06-27 10:09
I will be honest, I had to uninstall it because updates became unmanageable to me. In any case I am just not motivated enough to mess with it at this time.

**Comment by HBrinkman** [comment] 2017-08-24 17:29
I can't register either. Could you tell me if you're going to fix this? Thank you!

**Comment by forslund** [comment] 2017-08-24 18:58
Hi @HBrinkman currently we're having some issues with the pairing. We believe it's a server issue and are working on it. You can join our chat at chat.mycroft.ai for updates.

**Comment by fdh0** [comment] 2018-06-09 10:27
I can't register either. Could you tell me when the issue will be fixed?

**Comment by forslund** [comment] 2018-06-09 15:11
@fdh0 can you describe the issue you're facing in more detail? As far as I know this is currently not an a problem for others.

**Comment by forslund** [comment] 2018-07-21 22:04
Since there's been two major releases since last communication here I'm closing the issue. if you're still having problems let me know and we'll get it sorted. Thanks!

**Closed by forslund** 2018-07-21 22:04 UTC
