### ISSUE TITLE
Installation fails with "The 'packaging.requirements' package is required" - Ubuntu 17.10

### ISSUE THREAD

**Issue by 16NoCo** [MycroftAI/mycroft-core#1175] opened 2017-10-24 21:28 UTC
I had an old version of Mycroft which was not working, so I tried a fresh install : first from the GNOME extension and then manually with git (following installation instructions), but in both case the installation fails and I get this error : 

`ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.`

Might it be related to the old version I had (maybe there is some files left from it) ?

**Comment by aatchison** [comment] 2017-10-26 23:57
Hmm, I'm not sure what this refers to. Can you run mycroft in the git checkout with out the gnome extension?

**Comment by 16NoCo** [comment] 2017-10-27 08:43
I did remove the extension when I tried to install from git, so that didn't work. But since then I got the first system update since installing  Ubuntu 17.10 which fixed some broken things, and I don't longer get the import error.

Anyway, I still get an issue : when running `./start-mycroft.sh debug` or `./start-mycroft.sh cli`, it just says "Initializing..." and that the services are starting, but there is no command line interface (I can still write commands on the terminal) and I found no way to see if the other services are running. `ps -ef | grep -i -e mycroft` gives nothing, and my system settings don't list anything as application using the microphone.

**Comment by 16NoCo** [comment] 2017-10-27 09:16
I did remove the extension when I tried the git installation (`git clone ...` and `bash dev_setup.sh`, where I get the error line). Do you mean anything else by "checkout" ?

**Comment by ernstzlo** [comment] 2017-11-22 16:16
Same problem on my Ubuntu 17.10 (German language) which I updated.

I tried to remove the wreck of a non functioning Mycroft (Ubuntu 16.10) and install completely: here's all I did and  the complete output of the process

sudo rm mycroft-core -r

git clone https://github.com/MycroftAI/mycroft-core.git
Klone nach 'mycroft-core' ...
remote: Counting objects: 11698, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 11698 (delta 50), reused 83 (delta 44), pack-reused 11600
Empfange Objekte: 100% (11698/11698), 82.97 MiB | 1.54 MiB/s, Fertig.
Löse Unterschiede auf: 100% (7160/7160), Fertig.

cd mycroft-core

bash dev_setup.sh
Installing packages...
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
autoconf ist schon die neueste Version (2.69-11).
automake ist schon die neueste Version (1:1.15-6ubuntu1).
bison ist schon die neueste Version (2:3.0.4.dfsg-1build1).
g++ ist schon die neueste Version (4:7.2.0-1ubuntu1).
git ist schon die neueste Version (1:2.14.1-1ubuntu4).
libffi-dev ist schon die neueste Version (3.2.1-6).
libglib2.0-dev ist schon die neueste Version (2.54.1-1ubuntu1).
libjpeg-dev ist schon die neueste Version (8c-2ubuntu8).
libtool ist schon die neueste Version (2.4.6-2).
pkg-config ist schon die neueste Version (0.29.1-0ubuntu2).
python ist schon die neueste Version (2.7.14-2ubuntu1).
python-dev ist schon die neueste Version (2.7.14-2ubuntu1).
python-gobject-dev ist schon die neueste Version (3.24.1-2build1).
python-setuptools ist schon die neueste Version (36.2.7-2).
screen ist schon die neueste Version (4.6.1-1).
flac ist schon die neueste Version (1.3.2-1).
jq ist schon die neueste Version (1.5+dfsg-2).
libfann-dev ist schon die neueste Version (2.2.0+ds-3).
mpg123 ist schon die neueste Version (1.25.6-1).
portaudio19-dev ist schon die neueste Version (19.6.0-1).
python-virtualenv ist schon die neueste Version (15.1.0+ds-1).
s3cmd ist schon die neueste Version (2.0.0-1).
swig ist schon die neueste Version (3.0.10-1.2).
virtualenvwrapper ist schon die neueste Version (4.3.1-2).
curl ist schon die neueste Version (7.55.1-1ubuntu2.1).
libicu-dev ist schon die neueste Version (57.1-6ubuntu0.2).
libssl-dev ist schon die neueste Version (1.0.2g-1ubuntu13.2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Traceback (most recent call last):
  File "/home/ernst/.virtualenvs/mycroft/bin/easy_install", line 7, in <module>
    from setuptools.command.easy_install import main
  File "/home/ernst/.virtualenvs/mycroft/local/lib/python2.7/site-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extern.six.moves import filterfalse, map
  File "/home/ernst/.virtualenvs/mycroft/local/lib/python2.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
  File "/home/ernst/.virtualenvs/mycroft/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 71, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/ernst/.virtualenvs/mycroft/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 60, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

## I tried to start anyway
 ./start-mycroft.sh debug
Starting all mycroft-core services
Initializing...
Create /opt/mycroft/skills
[sudo] Passwort für ernst: 
Changing ownership of /opt/mycroft to user: ernst with group: ernst
der Eigentümer von '/opt/mycroft/skills' wurde von root:root in ernst:ernst geändert
der Eigentümer von '/opt/mycroft' wurde von root:root in ernst:ernst geändert
Starting background service bus
Starting background service skills
Starting background service audio
Starting background service voice
Starting cli

##but
screen -list
No Sockets found in /run/screen/S-ernst.

**Comment by penrods** [comment] 2017-11-22 17:23
Screen won't show you anything, we don't use it anymore.  You can try:
```ps aux | grep mycroft``` instead.  You should see output something like

```
osboxes@osboxes:~/mycroft-core$ ./start-mycroft.sh all
Starting all mycroft-core services
Initializing...
Starting background service bus
Starting background service skills
Starting background service audio
Starting background service voice
osboxes@osboxes:~/mycroft-core$ ps aux | grep mycroft
osboxes   8279  2.8  2.5 116880 26184 pts/1    S    12:18   0:00 python /home/osboxes/mycroft-core/mycroft/messagebus/service/main.py
osboxes   8282  3.3  3.2 799800 33408 pts/1    Sl   12:18   0:00 python /home/osboxes/mycroft-core/mycroft/skills/main.py
osboxes   8285  2.7  2.9 798768 30264 pts/1    Sl   12:18   0:00 python /home/osboxes/mycroft-core/mycroft/audio/main.py
osboxes   8288 13.4  4.4 981924 45096 pts/1    Dl   12:18   0:02 python /home/osboxes/mycroft-core/mycroft/client/speech/main.py
osboxes   8342  0.5  3.5 211612 35880 pts/1    D    12:19   0:00 /home/osboxes/mycroft-core/mimic/bin/mimic --version
osboxes   8359  0.0  0.0  21292   940 pts/1    S+   12:19   0:00 grep --color=auto mycroft
osboxes   8360  0.0  0.0   4508   704 pts/1    S    12:19   0:00 /bin/sh -c /home/osboxes/mycroft-core/msm/msm default
osboxes   8361  0.0  0.3  19984  3252 pts/1    S    12:19   0:00 /bin/bash /home/osboxes/mycroft-core/msm/msm default
osboxes   8366  0.0  0.5 173384  5420 pts/1    Sl   12:19   0:00 curl -s https://raw.githubusercontent.com/MycroftAI/mycroft-skills/master/.gitmodules
osboxes  24663  0.0  0.1 205740  1780 pts/17   S    Nov21   0:00 paplay /tmp/mycroft/cache/tts/5cf8a87973ddcf2e6a985f7c2e21622d.wav --stream-name=mycroft-voice
```

The top processes are the system, the bottom are subprocess MSM triggered at startup to update skills from the web and a PulseAudio subprocess while Mycroft is speaking to me.

Are you seeing anything similar?  This was under Ubuntu 16.04, so perhaps 17.10 has changed something.  I can give that a shot myself.

**Comment by ernstzlo** [comment] 2017-11-23 10:07
Thank you for your help

oh ...no screen? 
Perhaps someone could consider to have a look into the doc (the README.md is linking to:
https://docs.mycroft.ai/development/running
where in the Part "interacting with Mycroft" one is told to use screens .... ;-)
anyway
First, my **output** is this
`
ernst@ernst-breitlap:~/mycroft-core$ ./start-mycroft.sh all

Starting all mycroft-core services

Initializing... 
Starting background service bus
Starting background service skills
Starting background service audio
Starting background service voice

ernst@ernst-breitlap:~/mycroft-core$ ps aux | grep mycroft

ernst    11456  0.0  0.0  15924  1092 pts/0    S+   10:41   0:00 grep --color=auto mycroft
`
As my mycroft isn't listening, (my neighbor asked me, who the H*LL this mycroft is, I'm yelling at)  - or if listening is completely ignoring me - how can I manage to type some commands to Mycroft if the screen CLI isn't used any more ??

**Comment by ernstzlo** [comment] 2017-11-23 10:23
Shouldn't the services be listed here? For me it seems, that it isn't running, so the error, occuring while installing: 

ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

seemed to lead to a not functioning system:

service --status-all
 [ + ]  acpid
 [ - ]  alsa-utils
 [ - ]  anacron
 [ + ]  apache-htcacheclean
 [ + ]  apache2
 [ - ]  apparmor
 [ + ]  apport
 [ + ]  avahi-daemon
 [ - ]  bluetooth
 [ - ]  cgmanager
 [ - ]  cgproxy
 [ - ]  console-setup.sh
 [ + ]  cron
 [ + ]  cups
 [ + ]  cups-browsed
 [ + ]  dbus
 [ - ]  dns-clean
 [ - ]  dnsmasq
 [ + ]  grub-common
 [ - ]  hddtemp
 [ - ]  hwclock.sh
 [ + ]  irqbalance
 [ - ]  kerneloops
 [ - ]  keyboard-setup.sh
 [ + ]  kmod
 [ + ]  lightdm
 [ + ]  lm-sensors
 [ + ]  mysql
 [ + ]  network-manager
 [ + ]  networking
 [ - ]  nmbd
 [ - ]  openvpn
 [ - ]  plymouth
 [ - ]  plymouth-log
 [ + ]  postfix
 [ - ]  pppd-dns
 [ + ]  procps
 [ + ]  resolvconf
 [ - ]  rsync
 [ + ]  rsyslog
 [ - ]  runmbbservice
 [ - ]  samba
 [ - ]  samba-ad-dc
 [ - ]  saned
 [ - ]  screen-cleanup
 [ - ]  smbd
 [ + ]  speech-dispatcher
 [ - ]  thermald
 [ + ]  udev
 [ + ]  ufw
 [ + ]  unattended-upgrades
 [ - ]  uuidd
 [ + ]  virtualbox
 [ - ]  virtualbox-guest-utils
 [ + ]  whoopsie
 [ - ]  x11-common
 [ - ]  zoneminder

**Comment by forslund** [comment] 2017-11-23 10:33
The Mycroft processes aren't installed as services so they won't be listed there. However your previous test with:

`ps aux | grep mycroft` would have showed them if they were running. So mycroft can probably not start due to the failure in the installation script. I'm currently installing ubuntu 17.10 on a VM to see if I can recreate the issue

**Comment by forslund** [comment] 2017-11-23 16:05
I don't see this issue in my tests, I've googled around and found this: https://github.com/pyinstaller/pyinstaller/issues/2162

Are you on a 32 bit cpu and/or OS?

**Comment by ernstzlo** [comment] 2017-11-24 12:35
Ubuntu 17.10 (artful)
GNOME 3.26.1 (Ubuntu)
Typ des Betriebssystems 64-bit
Kernel 4.13.0-17-generic (#20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017)
OS-Type Linux
GCC-Version 7 (x86_64-linux-gnu)
Xorgversion 1.19.5 (15 October 2017  05:51:19PM)

The problem is: As far as I understand it, mycroft is built within a virtual environement, so everything a normal user can do "outside it" will never solve the problem.
Ubuntu 17.10 is running with python 3 - the virtual machine with 2.7 (I found python2.7 in my home/.virtualenvs/mycroft/bin folder)
I'm miles away of unterstanding the installation process, so I don't know, why my Ubuntu 17.10 is reacting differently than your Ubuntu 17.10.

**Comment by forslund** [comment] 2017-11-24 12:43
That is weird indeed, I upgraded mine from 17.04 so it might have some extra packages or something. Maybe you could try to remove the virtualenv and start from scratch.

```
rm -rf ~/.virtualenvs/mycroft
cd YOUR/PATH/mycroft-core
./dev_setup.sh
```

**Comment by ernstzlo** [comment] 2017-11-24 13:54
First of all, it seemed to have worked
with
./start-mycroft.sh debug
the cli window is there, mycroft is asking for activation.

The deletion of the virtualenvs/mycroft has done the job

THANK YOU VERY MUCH!

Do you want the installation protocol? there are several Warnings and an error message

**Comment by forslund** [comment] 2017-11-24 14:41
My guess is that something didn't quite download correctly the first time and redoing the entire process fixed it.

Some warnings are expected during the process (for example while building some libraries), shouldn't be any errors though. If you post the log (for example on pastebin.com) I'll look through it and see what I can determine.

**Comment by ernstzlo** [comment] 2017-11-24 15:12
https://pastebin.com/u/ernst_zlo

Again thank you for your Help.

I think, as I updated my Ubuntu serveral times since I first installed mycroft, that the .virtualenvs/mycroft wich went out of order some months ago was simply corrupted / outdated.

A hint in the doc's when NOT installing the first time would be helpful for others.
And a section how to completely uninstall.

**Comment by forslund** [comment] 2017-11-24 16:06
I think there's no big issues from what I can see. A bit weird that `cairo` isn't found but I don't _think_ that's critical...

**Comment by forslund** [comment] 2018-01-10 07:48
Closing this issue since it seem to have been resolved. Pinging @KathyReid for the docs request above.

**Closed by forslund** 2018-01-10 07:48 UTC
