### ISSUE TITLE
The code doesn't pass the flakes static checks

### ISSUE THREAD

**Issue by elopio** [MycroftAI/mycroft-core#18] opened 2016-05-20 22:30 UTC
⟫ pyflakes .
./mycroft/client/text/cli.py:44: local variable 'e' is assigned to but never used
./mycroft/client/speech/listener.py:350: local variable 'e' is assigned to but never used
./mycroft/client/speech/main.py:90: local variable 'e' is assigned to but never used
./mycroft/client/speech/wakeword_recognizer.py:5: 'sys' imported but unused
./mycroft/client/speech/wakeword_recognizer.py:7: 'from pocketsphinx import *' used; unable to detect undefined names
./mycroft/client/speech/wakeword_recognizer.py:46: Decoder may be undefined, or defined from star imports: pocketsphinx
./mycroft/client/speech/wakeword_recognizer.py:56: Decoder may be undefined, or defined from star imports: pocketsphinx
./mycroft/util/setup_base.py:19: local variable 'e' is assigned to but never used
./mycroft/util/setup_base.py:22: local variable 'e2' is assigned to but never used
./mycroft/messagebus/service/ws.py:36: local variable 'e' is assigned to but never used
./mycroft/messagebus/service/main.py:2: 'tornado' imported but unused
./mycroft/skills/intent/__init__.py:27: local variable 'e' is assigned to but never used
./mycroft/skills/wolfram_alpha/__init__.py:106: local variable 'e' is assigned to but never used
./mycroft/skills/weather/owm_repackaged/__init__.py:14: 'timeutils' imported but unused
./mycroft/skills/weather/owm_repackaged/owmhttpclient.py:69: 'urlopen' imported but unused
./mycroft/pairing/client.py:1: 'json' imported but unused
./mycroft/pairing/client.py:4: 'sys' imported but unused
./test/skills/skill_tester.py:2: 'unittest' imported but unused

**Comment by ikeydoherty** [comment] 2016-05-21 02:12
@elopio i would argue this is a duplicate of (or candidate for merge with) #4

**Comment by ikeydoherty** [comment] 2016-05-21 02:13
@elopio also see #2 where I iterated these issues that you've raised.

**Comment by Wolfgange3311999** [comment] 2016-05-21 16:42
@ikeydoherty I could be wrong but it seems like autopep8 only deals with formatting whereas pyflakes deals with unused variables and imports.

**Comment by ryanleesipes** [comment] 2016-05-23 23:34
If someone would be so kind as to volunteer to focus in on these, that would be awesome.

**Comment by aatchison** [comment] 2016-05-24 01:02
I started to knock out some I think. It's mostly just getting rid of unused
imports and such. Should be fairly easy. We need to integrate the license
headers asap though because everyone will have to rebase.

**Comment by ryanleesipes** [comment] 2016-05-26 18:30
Erroneously closed this, time to get to fixing!

**Comment by ryanleesipes** [comment] 2016-05-27 16:51
PR #60 addresses this.

**Closed** 2016-05-27 17:04 UTC
Labels: bug, enhancement
