### ISSUE TITLE
The dev_setup.sh script should ensure that it is not run with sudo, or at least ask.

### ISSUE THREAD

**Issue by LongBoolean** [MycroftAI/mycroft-core#32] opened 2016-05-23 18:31 UTC
After going through the register process the mycroft client doesn't seem to realize that it has been registered and continues to say that the device is not registered and gives a registration code. 
Restarting all of mycroft's processes after registration, and then restarting has no effect. The website itself appears to have worked, the device id on the web page matches the id in the identity.json file on my machine. 

commit: 9aa9f47f720736e0330854bd0d9ef5af0604808c

**Comment by aatchison** [comment] 2016-05-23 18:51
You might want to remove ~/.virtualenv and ~/.mycroft ; try again. Let me know what happens.

**Comment by aatchison** [comment] 2016-05-23 19:10
I can confirm that a fresh checkout, virtualenv, and build works for me. Can you confirm @LongBoolean ?

**Comment by LongBoolean** [comment] 2016-05-23 19:30
Well that did seem to solve the that problem, now I am having issues with it just saying "go ahead" instead of hearing what I say

**Comment by aatchison** [comment] 2016-05-23 19:31
We might be having some recognizer issues again. Have you tried just "Mycroft" as the wake word?

**Comment by LongBoolean** [comment] 2016-05-23 19:31
aww I see, I get this: `/bin/sh: 1: /home/nick/.virtualenvs/mycroft/local/lib/python2.7/site-packages/speech_recognition/flac-linux-i386: Permission denied`

**Comment by LongBoolean** [comment] 2016-05-23 19:34
if run `./start.sh voice` with sudo it works fine, without I get the "go ahead" problem

**Comment by aatchison** [comment] 2016-05-23 19:35
It seems that maybe you ran dev_setup.sh or something as sudo as some point?

**Comment by LongBoolean** [comment] 2016-05-23 19:38
yes, If I don't run dev_setup.sh as sudo, pip won't pull down any packages

**Comment by aatchison** [comment] 2016-05-23 19:46
That shouldn't be the case, and you should never run as sudo, as the virtualenv is created in your user directory, in the case of sudo /root/.virtualenv

**Comment by LongBoolean** [comment] 2016-05-23 19:49
that is incorrect, as you can see from the error: `/bin/sh: 1: /home/nick/.virtualenvs/mycroft/local/lib/python2.7/site-packages/speech_recognition/flac-linux-i386: Permission denied`
.virtualenvs is in fact in my home directory

**Comment by aatchison** [comment] 2016-05-23 19:56
I'm sorry, but I don't know why that would happen. Hmm. Any thoughts @channel?

**Comment by LongBoolean** [comment] 2016-05-23 20:06
would you like me to edit the name of this issue to better reflect the current problem?

**Comment by aatchison** [comment] 2016-05-23 20:07
Yeah, that sounds like a good idea. I wonder what is going on here?

**Comment by Cliabhach** [comment] 2016-05-23 20:08
Can you show the full set of permissions on that file? `ls -l /home/nick/.virtualenvs/mycroft/local/lib/python2.7/site-packages/speech_recognition/` should do the job.

**Comment by LongBoolean** [comment] 2016-05-23 20:12
```
$ ls -l /home/nick/.virtualenvs/mycroft/local/lib/python2.7/site-packages/speech_recognition/
total 1388
-rwxr--r-- 1 root root 882460 May 23 14:14 flac-linux-i386
-rwxr-xr-x 1 root root 194676 May 23 14:14 flac-mac
-rwxr-xr-x 1 root root 262144 May 23 14:14 flac-win32.exe
-rw-r--r-- 1 root root  33784 May 23 14:14 __init__.py
-rw-r--r-- 1 root root  32282 May 23 14:15 __init__.pyc
-rw-r--r-- 1 root root   1237 May 23 14:14 __main__.py
-rw-r--r-- 1 root root   1087 May 23 14:15 __main__.pyc
```

**Comment by LongBoolean** [comment] 2016-05-23 20:12
root owns everything!!!

**Comment by Cliabhach** [comment] 2016-05-23 20:16
Interesting that the mac and windows binaries have group- and world-execute permission. At any rate, something's up with the way pip is configured and/or running. Not exactly sure what, though. You said that pip wouldn't download packages when you ran dev_setup.sh without sudo - did it give any specific errors?

**Comment by aatchison** [comment] 2016-05-23 20:19
Is it possible that you checked out as root?

**Comment by LongBoolean** [comment] 2016-05-23 20:21
no I did not checkout as root or with sudo, and for the record `sudo` and `root` are not synonyms.

**Comment by aatchison** [comment] 2016-05-23 20:22
Right, just wondering why it root would get ownership.

**Comment by LongBoolean** [comment] 2016-05-23 20:22
```
$ ./dev_setup.sh 
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/home/nick/.virtualenvs/mycroft/lib/python2.7/site-packages/test-easy-install-8020.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /home/nick/.virtualenvs/mycroft/lib/python2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

```
hmmm these results seem different than what I remembered, but either way it still has issues.

**Comment by aatchison** [comment] 2016-05-23 20:24
What happens if you:
chown -Rv nick:nick ~/.virtualenvs/mycroft ?

**Comment by LongBoolean** [comment] 2016-05-23 20:24
`dev_setup.sh` is what sets these files up right? How does `dev_setup.sh` decide which user should own it?

**Comment by aatchison** [comment] 2016-05-23 20:25
VIRTUALENV_ROOT=${VIRTUALENV_ROOT:-"${HOME}/.virtualenvs/mycroft"}

It sets up in whatever user's home dir is as run as.

**Comment by LongBoolean** [comment] 2016-05-23 20:27
you mean `sudo chown -Rv nick:nick ~/.virtualenvs/mycroft` right? :)

**Comment by aatchison** [comment] 2016-05-23 20:28
lol, yes :)

**Comment by LongBoolean** [comment] 2016-05-23 20:30
that gets rid of the first error in `dev_setup` then it stops here:
```
writing pocketsphinx.egg-info/PKG-INFO
error: [Errno 13] Permission denied: 'pocketsphinx.egg-info/PKG-INFO'
```

**Comment by aatchison** [comment] 2016-05-23 20:31
ok, now chown  mycroft-core/pocketsphinx perhaps

**Comment by LongBoolean** [comment] 2016-05-23 20:33
this command: `sudo chown -Rv nick:nick ~/gitHub/mycroft-core/pocketsphinx-python/`

**Comment by LongBoolean** [comment] 2016-05-23 20:34
I think I'm going to remove the pocketsphinx dir entirly and let it re download

**Comment by aatchison** [comment] 2016-05-23 20:35
Yeah, starting over sounds like a good idea:)

**Comment by clusterfudge** [comment] 2016-05-23 20:41
@LongBoolean we really *really* (as in I put a lot of effort into this) shouldn't need to use sudo for the dev_setup.sh script. The goal of that script is to create an isolated (and in the user space) development environment without scattering bits across the host. The build_host_setup.sh script is the exception here, and it uses sudo internally to apt-get install the native dependencies. If you're having trouble running without sudo (or normally, as I call it 😄 ), then we should dig into that.

**Comment by LongBoolean** [comment] 2016-05-23 20:47
Somewhat related, after an ubuntu update, `workon mycroft` no longer works on my machine and I get this error every time I open a new shell: 
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/virtualenvwrapper/hook_loader.py", line 16, in <module>
    from stevedore import ExtensionManager
ImportError: No module named stevedore
virtualenvwrapper.sh: There was a problem running the initialization hooks. 

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python2 and that PATH is
set properly.
nick@NicksDesktop:~$
```
So I've been living dangerously for the past few weeks. :)

**Comment by aatchison** [comment] 2016-05-24 02:12
hmm.
Try:
`pip install -r requirements.txt`  
Then perhaps:
'pip install stevodore'
if that doesn't work?

**Comment by Wolfgange3311999** [comment] 2016-05-24 14:57
@longboolean: If I were you I would just reset all your files to nick:nick with `sudo chown -Rv nick:nick /home/nick/` assuming that is your home directory.

**Comment by Chas20022002** [comment] 2016-05-26 13:27
On step 2 of new install.  IE Run Dev_Setup.sh

Logged in as root, 
in mycroft-core folder, 
but when I attempt to sh dev_setup.sh I get "This script should not be run as root or with sudo."

I have no idea how to run this without sudo?  I created a new user Chas2002, but of course this creates a directory related to Chas2002.  So, I navigate back but /root throws "permission denied."

I think I'm missing a step somewhere.

Thanks,
Chas

**Comment by Cliabhach** [comment] 2016-05-26 13:35
@Chas20022002 Right, to switch users inside a session you'll want to use the `su username` command; here, it'd be `su Chas2002`. Of course, you could also just login to the host machine as Chas2002 before working on Mycroft (that's the intended behavior).

Developing code as root causes problems like the ones this ticket was created to address, so we want you not to do that if possible.

**Comment by Cliabhach** [comment] 2016-05-26 13:36
You cloned/downloaded the original code as root, right? You'd probably be best off re-cloning it as your new user.

**Comment by Chas20022002** [comment] 2016-05-26 13:40
Ah, okay.  Yes, placed the build in root.  Will do as you suggest and place the build under an su user.  Thanks.

**Comment by LongBoolean** [comment] 2016-05-26 20:26
@Wolfgange3311999 yes that would fix my problems for sure, but the point is to make sure that the dev_setup script does the right thing, if it doesn't then it should be fixed so that other people won't have this issue aswell.

**Comment by aatchison** [comment] 2016-05-27 02:17
I think I closed this issue too soon:)

**Comment by clusterfudge** [comment] 2016-05-27 03:59
@LongBoolean You opened this original ticket (which has gotten away from us a bit). I think the original title of the issue (mycroft not pairing in ubuntu) captures your pain most accurately, and the title has shifted a bit with respect to tangential issues. The most telling message from the thread (to me, at least) is the following
```
yes, If I don't run dev_setup.sh with sudo, pip won't pull down any packages
```
I think this is the original issue we need to diagnose. If you agree, the following information would be helpful

1) version/distro of OS
2) global version of pip and virtualenv
3) the full output of build_host_setup.sh and dev_setup.sh when run from scratch (stdout and stderr).

My current suspicion is that your other issues stem from this; with some processes running as different users, and the skills process paired (with an identity file living in /home/${USER}/.mycroft/identity/identity.json) and client not paired (identity file in /root/.mycroft/identity/identity.json). You confirming the existence of those two files would be a strong indicator we're on the right track.


thanks for your patience on this.

**Comment by LongBoolean** [comment] 2016-05-27 05:27
@clusterfudge The original problem had to do with moving from the mycroft repo to the mycroft-core repo, deleting the .mycroft and .virtualenvs directories fixed the problem. Does this mean that something was not getting added that should have been if those directories where present, perhaps. It did seem to me that the tangential issues seemed to be more at the core of the problems that I have been having so because the previous looked solved and while on the topic of the tangential issues, and with the approval of @aatchison, I decided to change the title. Title the issue as you wish. What ever is more descriptive.

I agree that permissions is currently an issue that effects the mycroft installation process in several areas. For example, when ever a new skill is added I need to run `./start.sh skills` with `sudo` the first time in order for the skill to load.(exactly why I do not know) Otherwise I get a permission denied error. After that the skill loads fine without sudo.

ubuntu 14.04 (3.13.0-86-generic)
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
virtualenv 14.0.6

It would be a little hard to run every thing from scratch without reinstalling my OS(I no longer get the pip errors because all of the needed packages are installed), although I suppose I could set up a virtual machine with default ubuntu and attempt to get mycroft working without the use of sudo. 
Although come to think of it I could try uninstalling one of the packages that dev_setup installs(hopefully something that is specific to just mycroft so I don't break anything else on my system) and then run dev_setup to see if I get the error again.

Yeah I know you guys have a lot of work on your plates, and have to deal with more than just development duties.

**Comment by ryanleesipes** [comment] 2016-05-30 21:26
This got merged, yes?

**Comment by Cliabhach** [comment] 2016-05-30 21:29
@ryanleesipes Pull request 43 was merged, yes.

**Closed** 2016-05-31 17:52 UTC
Labels: bug
