### ISSUE TITLE
Audioservice may fail to restore volume

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2708] opened 2020-09-30 06:46 UTC
Audio failed to restore volume in some instances. 

May be caused by parallel waits being created by `wait_for_message` with the same message?

At the very least, the current audioservice may be re-assigned to None while the message is being waited on. So the previous check for `self.current` is no longer accurate. Should probably re-check in the inner function.

#### relevant logs
```
2020-09-30 03:37:48.280 | INFO     |   439 | mycroft.audio.speech:mute_and_speak:127 | Speak: Here is this hour's news on NPR News Now.
2020-09-30 03:37:52.405 | INFO     |   439 | mycroft.audio.speech:mute_and_speak:127 | Speak: Give me a moment to check for that
2020-09-30 03:37:55.083 | INFO     |   439 | audioservice_simple:add_list:75 | Track list is [['file:///tmp/mycroft/cache/NewsSkill/stream', 'audio/mpeg']]
2020-09-30 03:37:55.086 | INFO     |   439 | audioservice_simple:play:147 | Call SimpleAudioServicePlay
2020-09-30 03:37:55.176 | INFO     |   439 | audioservice_simple:_play:82 | SimpleAudioService._play
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.25.13; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/mycroft/cache/NewsSkill/
Playing MPEG stream 1 of 1: stream ...

MPEG 1.0 L III cbr128 44100 stereo

Title:   
2020-09-30 03:38:00.342 | INFO     |   439 | audioservice_simple:stop:152 | SimpleAudioServiceStop
2020-09-30 03:38:00.363 | INFO     |   439 | mycroft.audio.speech:mute_and_speak:127 | Speak: Here is this hour's news on NPR News Now.

mpg123: death by SIGTERM
2020-09-30 03:38:03.111 | INFO     |   439 | audioservice_simple:add_list:75 | Track list is [['file:///tmp/mycroft/cache/NewsSkill/stream', 'audio/mpeg']]
2020-09-30 03:38:03.112 | INFO     |   439 | audioservice_simple:play:147 | Call SimpleAudioServicePlay
2020-09-30 03:38:03.168 | INFO     |   439 | audioservice_simple:_play:82 | SimpleAudioService._play
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.25.13; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/mycroft/cache/NewsSkill/
Playing MPEG stream 1 of 1: stream ...

MPEG 1.0 L III cbr128 44100 stereo

Title:   
2020-09-30 03:38:17.459 | INFO     |   439 | audioservice_simple:stop:152 | SimpleAudioServiceStop
2020-09-30 03:38:23.158 | ERROR    |   439 | concurrent.futures | exception calling callback for <Future at 0x7f482e1fa0 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/pyee/_executor.py", line 60, in _callback
    self.emit('error', exc)
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/pyee/_base.py", line 111, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/pyee/_base.py", line 83, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mycroft/mycroft-core/mycroft/audio/audioservice.py", line 338, in _restore_volume_after_record
    restore_volume()
  File "/home/mycroft/mycroft-core/mycroft/audio/audioservice.py", line 330, in restore_volume
    self.current.restore_volume()
AttributeError: 'NoneType' object has no attribute 'restore_volume'
```

**Comment by forslund** [comment] 2020-10-01 19:51
I looked this over a bit. I think the problem is that the handler for restore volume can wait for upto 8 seconds. This is a race condition at heart.

Basically what I think happens is

- check that `self.current` is valid
- Start waiting for message
- Stop occurs, clearing `self.current`
- wait completes and launches the callback
- callback tries to access `self.current`

First, I think the audio service backend _should_ be able to handle this case, restoring volume on stop.

The race condition can be handled more gracefully in two ways
- more aggressive locking with `self.service_lock`
- work with local copies
Ex:
```python
    def _restore_volume_after_record(self, message=None):
        """
            Restores the volume when Mycroft is done recording.
            If no utterance detected, restore immediately.
            If no response is made in reasonable time, then also restore.
            Args:
                message: message bus message, not used but required
        """
        current = self.current # Create local reference to current active service

        def restore_volume():
            LOG.debug('restoring volume')
            current.restore_volume()  # restore the service that were active when this was initiated

        if current:
            self.bus.on('recognizer_loop:speech.recognition.unknown',
                        restore_volume)
            speak_msg_detected = self.bus.wait_for_message('speak',
                                                           timeout=8.0)
            if not speak_msg_detected:
                restore_volume()
            self.bus.remove('recognizer_loop:speech.recognition.unknown',
                            restore_volume)
        else:
            LOG.debug("No audio service to restore volume of")
```

**Comment by krisgesling** [comment] 2020-10-02 00:17
When a service is stopped without restoring the volume, would the volume still be muted when it's restarted?
This approach seems to address that possibility.

Also is there any danger in something like:
1. Utt 1 - wake word received - service muted
2. Utt 1 - user speaking - "stop"
3. Utt 2 - wake word received - service muted
4. Utt 1 - service stopped
5. Utt 1 - service volume restored
  **music now playing**
6. Utt 2 - user speaking over music

**Comment by forslund** [comment] 2020-10-02 06:16
The case you describe shouldn't be possible with the current simple audio service backend since the stop command exits the play loop. But would be implementation dependant. Basically how the service react to a restore volume after stop.

Using the lock more might be safer in that case leaving less to the implementation...

**Comment by forslund** [comment] 2020-10-05 07:18
I pushed a branch with some [locks](https://github.com/forslund/mycroft-core/tree/bugfix/audioservice-locks), it should remove the the error message but I'm not sure it'll solve the issue (which I haven't managed to reproduce yet)

**Comment by forslund** [comment] 2024-09-08 08:33
Closing Issue since we're archiving the repo

**Closed by forslund** 2024-09-08 08:33 UTC
Labels: Type: Bug - complex
