### ISSUE TITLE
Package as Snap or Flatpak

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#1723] opened 2018-08-10 06:05 UTC
This is related to #246. Packaging Mycroft as a snap or flatpak would significantly simplify installation on a variety of platforms. However, this is not a trivial task. Here's a list of steps I see towards making this happen (with either Snap or Flatpak):

 - [ ] Package hello world Python app
 - [ ] Package Python app using `aplay` to play a wav file
 - [ ] Package Python app that uses `PyAudio` to listen to the microphone
 - [ ] Attempt packaging Mycroft Core (For Snap, [start here](https://github.com/MycroftAI/snapcraft-mycroft-core))

**Comment by diddledan** [comment] 2018-08-31 09:45
I've built a snap as part of the Snapcrafters project. It's still experimental right now, but seems to be fairly good.

**Comment by rahmanshaber** [comment] 2018-09-04 05:58
what release you used to made it??

**Comment by diddledan** [comment] 2018-09-04 09:41
it's currently 18.2.12

**Comment by vipulgupta2048** [comment] 2018-10-07 10:12
Hey, do we still have the requirement for a snap package? i am new to packaging and would like to give a shot at this,

**Comment by pseams** [comment] 2018-10-10 14:14
What needs to be done to allow access to that? I'm very new to this and don't understand most of it.

**Comment by countcretinos** [comment] 2020-03-29 18:25
I have a initial Flatpak setup for building MyCroft with dependencies. It's not working as-is but prove useful as a starting point for official Flatpak support.

- [Here's](https://github.com/countcretinos/mycroft-core/blob/feature/flatpak/flatpak/io.github.countcretinos.mycroft-core.json) my Flatpak manifest
- With Flatpak, builds are supposed to be, AFAIU, reproducible. Therefore exact urls to PyPi dependency archives must first be generated with [flatpak-pip-generator](https://docs.flatpak.org/en/latest/python.html). That tool does not work 100% proof with all dependencies so they need to be fixed afterwards in the resulting manifest.
- Flatpak wants your application to reside at /app. This doesn't go well well with MyCroft since it's assumed that the application is installed to /opt/mycroft and var-files go there as well. Also fann2 PyPi package doesn't look for fann2 libs under /app so it needs to be patched/fixed

**Comment by ChanceNCounter** [comment] 2020-03-29 18:58
There are some downsides I think folks should keep in mind while they're packaging Mycroft, bearing in mind that I'm just another community member like you guys and not an employee, so, feel free to ignore me 😛

1. Make sure it's loudly and visibly an UNOFFICIAL package. We are approached regularly in chat by people who are fighting with abandoned, third-party packages. People get the impression that these packages were created and abandoned by MycroftAI, and it leaves a bad taste in their mouth regarding both the company and the project.

2. Desktop launchers and etc. WILL NOT WORK in a sandbox, unless *you* do the work required to make that possible. Indeed, if they could, that would defeat the purpose of the sandbox. You don't want programs you don't know shutting your computer down.

3. If you *do* want to expose the message bus to the host machine, the package will need to be configured for that.

4. If you do this using the dev repo, rather than a Picroft image, you're distributing software via an installer than sends and accepts unauthenticated instructions in the clear (the CLI bitches about this to make sure you notice.) The images don't have that problem, because they go directly to consumers. The images were made for specific environments.

As long as everybody who plays with it has that stuff in mind, cool beans.

**Comment by krisgesling** [comment] 2020-03-30 03:26
Hey all, the good news is that we are working on some official Snap packages at the moment. Huge thanks to @diddledan for all his work on this over the years. He's a Snapcraft Master! 

We've started by Snapping some component technologies first to get our heads around Snapcraft and the whole Snappy ecosystem:
1. For a Mimic1 snapcraft config see [this branch of the Mimic1 repo](https://github.com/MycroftAI/mimic1/tree/feature/snap-package).
2. Next up is Precise. 
3. Then if all goes well, we will move onto a full Mycroft Snap.

If you want to try the Snap config out yourself:

1. Clone the Mimic1 repo and checkout the "feature/snap-package" branch
  ```
git clone https://github.com/MycroftAI/mimic1
cd mimic1
git checkout feature/snap-package
```

2. Install snapcraft and multipass (a container orchestration tool used by snapcraft)
  ```
sudo snap install snapcraft
sudo snap install multipass
```

3. From the Mimic1 directory run `snapcraft` to build the Snap (this will take a while)
```
snapcraft
```

4. Install the Snap you built:
```
sudo snap install --dangerous *.snap
```
_The `--dangerous` flag is to highlight that you haven't gotten this from the Snap store. This means it hasn't been reviewed by Canonical or another Snap Store provider. You're confirming that it's your responsibility to know what's in the source code and what it could do to your system._

5. Run the Snap 
```
mimic -t "Hello world"
mimic -t "All standard Mimic commands should work" -voice slt
```

If you're interested in helping us out and testing new Snaps as they're built, join us in the [Linux Packaging channel on Mycroft Chat](https://chat.mycroft.ai/community/channels/ubuntu-apt-packaging).

**Comment by forslund** [comment] 2020-05-20 13:31
[snapcraft-mycroft-core](https://github.com/mycroftai/snapcraft-mycroft-core) has been updated with a now working version based on @diddledan's work and is avaliable on as an "edge" package. I'm closing this issue as of this. (separate request for flatpak can be opened as a new issue).

**Closed by forslund** 2020-05-20 13:31 UTC
Labels: help wanted
