### ISSUE TITLE
System sound volume different from Audio Service VLC volume

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-core#1375] opened 2018-01-20 11:24 UTC
volume control in mark1 works perfectly, the trouble is that suddenly any audio played by audio service vlc is in very low volume

mycroft speaks very loud, internet radio is barely audible

i can confirm this is with vlc in audio service only, mpg123 works

**how to replicate**

i am not sure how to replicate

- install vlc
- install [internet radio skill](https://github.com/jarbasAI/skill-internet-radio)
- play some radio
- verify audio volume works as expected

i think after issuing a call to cvlc by command in [this skill](https://github.com/JarbasAI/skill-youtube-audio) is when trouble started, but i don't think i ever triggered the skill, i went out to dinner and got back to a screwed up volume

- install that skill
- say "play {music} from youtube"
- maybe this screws things up or maybe it was not the cause
- i do not think the skill is functional, do not expect actual song to play (but it is supposed to)

**what i have tried**

changing alsamixer master volume does nothing

pactl  set-sink-volume 0 +X%   does nothing

pacmd i have no idea what i'm doing but no success either

 i seem to have increased volume with pactl, in amixer i now get 720% instead of 100%

Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Front Left: Playback 471859 [720%] [on]
  Front Right: Playback 471859 [720%] [on]

no impact in actual output, what audio shenanigans are going on in the mark1 ?

set flat-volumes = no in  /etc/pulse/daemon.conf to enable per-application volume control. - no change

reboot, no change

**possible cause:**

i believe i got this problem https://raspberrypi.stackexchange.com/questions/15148/wrong-alsa-volume-when-starting-playback after executing cvlc

**Comment by JarbasAI** [comment] 2018-01-20 11:45
update:

amixer -c 0 set Master xDB

works, but only to reduce volume, it never goes above a threshold

is like if for vlc the maximum volume is set too low, seems to be the vlc changing the output volume, not the system volume

**Comment by forslund** [comment] 2018-01-20 11:54
Thanks for reporting I'll try to replicate and see if I can debug.

Vlc has internal volume control and it's probably that volume that gets set to low at some point.

Another thing you can try is to delete the pulseaudio session files in /home/mycroft/.config/pulseaudio (from memory so I might have it slightly wrong)

**Comment by JarbasAI** [comment] 2018-01-20 11:55
ok, weird thing happened

i apt-purged vlc, figured if i reinstalled it would go back to default

without vlc installed everything works, seems it was the requirements.sh from the youtube skill that caused trouble

**Comment by JarbasAI** [comment] 2018-01-20 13:17
it happened again, i changed the youtube skill to use audio service, just to see if it would play

surprise, i could hear sound, very low

internet radio no longer works...

there was no command line call this time

**Comment by neterbg** [comment] 2018-05-06 20:58
The problem is caused by a time.sleep(2) function in mycroft-core/mycroft/audio/main.py (on line 334 in my version). When you call mycroft about something (e.g. what time is it), it reduces the volume of all pulse apps except his voice, so you can hear the answer, waits these 2 seconds (I don't know why), and increases the volume again so you can continue to listen the song. But when you call mycroft to stop the song, in these 2 seconds the vlc instance is killed and after that the increasing of the volume doesn't affect the pulse client for vlc (because there's no such client in that time). There's no problem if you remove the row with the sleep (for me, there's no problem if you reduce the seconds to 1 too). I don't know why there is such sleep there in first place, but I removed it for me and I don't see some problems caused by this.

**Comment by forslund** [comment] 2018-05-06 21:03
PR #1506 should fix this issue with vlc. It cleans up much of the logic around the audio ducking.

**Comment by krisgesling** [comment] 2020-09-24 07:10
Presuming fixed with the linked PR's. Please reopen if I'm mistaken.

**Closed by krisgesling** 2020-09-24 07:10 UTC
