### ISSUE TITLE
Registration/pairing doesn't work

### ISSUE THREAD

**Issue by skddc** [MycroftAI/mycroft-core#772] opened 2017-05-20 14:22 UTC
I cloned the repo, ran the setup script, and started Mycroft (on Arch Linux). Then I tried registering the device, as per https://docs.mycroft.ai/installing.and.running/pairing. However, I don't see a 6-digit code in any of the logs, but it tries to do a bunch of requests, that all result in 401 responses (both in master and dev branches).

CLI screen log:

```
2017-05-20 16:16:24,118 - SpeechClient - INFO - Wakeword Detected: hey mycroft
2017-05-20 16:16:24,156 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-05-20 16:16:25,073 - mycroft.client.speech.mic - DEBUG - Waiting for wake word...
2017-05-20 16:16:25,134 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/stt?lang=en-US&limit=1 HTTP/1.1" 401 38
2017-05-20 16:16:25,142 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-05-20 16:16:26,146 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-US", "session": "5cbb3e56-32a4-487b-88d6-b9e5e935fa1b", "utterances": ["pair my device"]}, "context": null}
2017-05-20 16:16:26,148 - mycroft.skills.intent_service - ERROR -
Traceback (most recent call last):
File "/home/basti/src/mycroft/mycroft-core/mycroft/skills/intent_service.py", line 54, in handle_utterance
normalize(utterance, lang), 100))
 2017-05-20 16:16:26,134 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
2017-05-20 16:16:26,142 - mycroft.client.speech.listener - WARNING - Access Denied at mycroft.ai
StopIteration
2017-05-20 16:16:26,150 - Skills - DEBUG - {"type": "intent_failure", "data": {"lang": "en-US", "utterance": "pair my device"}, "context": null}
2017-05-20 16:16:26,142 - SpeechClient - INFO - Utterance: ['pair my device']
```

Voice screen log:

```
2017-05-20 16:16:24,118 - SpeechClient - INFO - Wakeword Detected: hey mycroft
2017-05-20 16:16:24,156 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-05-20 16:16:25,073 - mycroft.client.speech.mic - DEBUG - Waiting for wake word...
2017-05-20 16:16:25,134 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/stt?lang=en-US&limit=1 HTTP/1.1" 401 38
2017-05-20 16:16:25,142 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-05-20 16:16:26,146 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-US", "session": "5cbb3e56-32a4-487b-88d6-b9e5e935fa1b", "utterances": ["pair my device"]}, "context": null}
2017-05-20 16:16:26,148 - mycroft.skills.intent_service - ERROR -
Traceback (most recent call last):
File "/home/basti/src/mycroft/mycroft-core/mycroft/skills/intent_service.py", line 54, in handle_utterance
normalize(utterance, lang), 100))
 2017-05-20 16:16:26,134 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
2017-05-20 16:16:26,142 - mycroft.client.speech.listener - WARNING - Access Denied at mycroft.ai
StopIteration
2017-05-20 16:16:26,150 - Skills - DEBUG - {"type": "intent_failure", "data": {"lang": "en-US", "utterance": "pair my device"}, "context": null}
2017-05-20 16:16:26,142 - SpeechClient - INFO - Utterance: ['pair my device']
```

Mycroft doesn't say anything when this happens and any voice commands all result in this same command an log.

**Comment by forslund** [comment] 2017-05-22 07:15
Can you check that the `/opt/mycroft/skills` directory exists and have the skill skill-pairing. If the skills directory is empty you can install the base skill-set with `./msm/msm default`

**Comment by skddc** [comment] 2017-05-22 08:37
Thanks, that was it. This information is missing from the Setup / Getting Started guides: https://docs.mycroft.ai/installing.and.running

**Comment by forslund** [comment] 2017-05-22 08:47
Glad it helped. The idea is that this should be automatic. Apparently it doesn't work all the time, I'll see if I can add a comment about this to the docs.

**Comment by skddc** [comment] 2017-05-22 09:01
Yeah, I thought this would be included in the dev setup script (which would make sense I think).

**Comment by djmitche** [comment] 2017-05-22 16:19
This was my issue too.  Pairing can't complete until the pairing skill is in place.  The "checking for updates" that occurs on startup should do this -- but it doesn't.

**Comment by djmitche** [comment] 2017-05-22 16:35
I modified the skills sync to log the output of `MSM_BIN + " update"`.  Here's what I get:

```
2017-05-22 12:30:10,144 - Skills - DEBUG - #######  Mycroft Skill Manager #######
2017-05-22 12:30:10,145 - Skills - DEBUG - Cloning repository
2017-05-22 12:30:10,145 - Skills - DEBUG - Cloning into 'skill-audio-record'...
2017-05-22 12:30:10,145 - Skills - DEBUG - error: waitpid for unpack-objects failed: No child processes
2017-05-22 12:30:10,145 - Skills - DEBUG - fatal: unpack-objects failed
2017-05-22 12:30:10,145 - Skills - DEBUG - error: waitpid for fetch-pack failed: No child processes
2017-05-22 12:30:10,145 - Skills - DEBUG - /home/dustin/mycroft-core/msm/msm: line 74: cd: skill-audio-record: No such file or directory
2017-05-22 12:30:10,145 - Skills - DEBUG - Skill installed!
2017-05-22 12:30:10,145 - Skills - DEBUG - Cloning repository
2017-05-22 12:30:10,145 - Skills - DEBUG - Cloning into 'skill-configuration'...
2017-05-22 12:30:10,145 - Skills - DEBUG - error: waitpid for unpack-objects failed: No child processes
2017-05-22 12:30:10,145 - Skills - DEBUG - fatal: unpack-objects failed
2017-05-22 12:30:10,145 - Skills - DEBUG - error: waitpid for fetch-pack failed: No child processes
2017-05-22 12:30:10,145 - Skills - DEBUG - /home/dustin/mycroft-core/msm/msm: line 74: cd: skill-configuration: No such file or directory
2017-05-22 12:30:10,145 - Skills - DEBUG - Skill installed!
2017-05-22 12:30:10,145 - Skills - DEBUG - Cloning repository
2017-05-22 12:30:10,145 - Skills - DEBUG - Cloning into 'skill-date-time'...
2017-05-22 12:30:10,145 - Skills - DEBUG - error: waitpid for unpack-objects failed: No child processes
2017-05-22 12:30:10,145 - Skills - DEBUG - fatal: unpack-objects failed
2017-05-22 12:30:10,146 - Skills - DEBUG - error: waitpid for fetch-pack failed: No child processes
2017-05-22 12:30:10,146 - Skills - DEBUG - /home/dustin/mycroft-core/msm/msm: line 74: cd: skill-date-time: No such file or directory
2017-05-22 12:30:10,146 - Skills - DEBUG - Skill installed!
...
2017-05-22 12:30:10,152 - Skills - DEBUG - Skill installed!
2017-05-22 12:30:10,152 - Skills - DEBUG - ls: cannot access '*/': No such file or directory
2017-05-22 12:30:10,152 - Skills - DEBUG - Installed!
```

**Comment by djmitche** [comment] 2017-05-22 16:39
Looking at the `msm` script, it has basically no error handling, and unconditionally says "Installed!" at the end..

**Comment by djmitche** [comment] 2017-05-22 18:08
I went to try to fix this.  So, two weird things:

1. I can't reproduce the git failure outside of msm being run inside the skill.  `msm update` works fine by hand, as does a `git clone`.
1. I added `set -e` to `msm` so that it exits on error, and back in `mycroft/skills/main.py` the subprocess.Popen object, `p`, has `p.returncode == 0`.  Trying to track that down, I wrote:
```python
p = subprocess.Popen( "exit 1", stderr=subprocess.PIPE, stdout=subprocess.PIPE, shell=True)
```
and still `p.returncode` is 0.  I can't figure out what is going on there. Running the same command in a Python REPL has `p.returncode == 1` as expected.

So, baffled, twice.

**Comment by forslund** [comment] 2017-05-22 18:32
I think it's the SIGCHLD thing that's causing 2. PR #754 will probably fix that. You can check by removing line 40 in `main.py`

```python
signal.signal(signal.SIGCHLD, signal.SIG_IGN)
```

**Comment by djmitche** [comment] 2017-05-22 18:50
That sounds very promising!

**Comment by iqtedar** [comment] 2017-06-13 06:52
Running <./mycroft.sh start -d> and entering the text "say Mycroft, register my device" gives you the six-character code, which you then enter at https://home.mycroft.ai, The registration and pairing are done, but the audio is not working.

**Comment by kfezer** [comment] 2017-06-13 16:08
So this sounds like a different issue. I'd try the forums or the picroft wiki for suggestions on getting audio working. 
https://github.com/MycroftAI/enclosure-picroft/wiki
https://community.mycroft.ai/
What device are you using and is it output or input that aren't working?

I'm also going to close this issue as that PR is merged and seems to have addressed the original problem.

**Closed by kfezer** 2017-06-13 16:08 UTC
Labels: priority: critical
