### ISSUE TITLE
Hourly error spoken: "Sorry I couldn't install default skills", and no hints as to why

### ISSUE THREAD

**Issue by nealmcb** [MycroftAI/mycroft-core#877] opened 2017-07-04 21:02 UTC
Can someone help out with https://community.mycroft.ai/t/error-occurred-installing-default-skills/1768 ?
I'm getting much the same thing, in errors spoken every hour.

While looking into where that happens, at [mycroft/skills/main.py line 69](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/main.py#L69), I see a separate issue with capturing the output, since it calls `subprocess.call()` with `stdout=subprocess.PIPE`.  As noted at  
https://docs.python.org/2/library/subprocess.html:
> Note Do not use stderr=PIPE with this function as that can deadlock based on the child process error volume. Use Popen with the communicate() method when you need a stderr pipe.

This code was introduced in #782, the patch for #781, replacing earlier code that did use Popen.
The error branch should at least print out the value of the exit code in variable `res`, and should probably also at least expose the output of the call to `msm default` via `logger.error()`

**Comment by forslund** [comment] 2017-07-05 09:28
Thanks for pointing this out. At the time we got no real info from msm regarding the cause of the failure but thanks to @el-tocino we now get detailed error messages and return codes that should be used.

I'll fix the `subprocess.call()` issue and add an error log on failure.

Seems like the install method gets called every time the wifi handler send out `mycroft.internet.connected` message on the message bus. appart from that I can't see any cyclic calls. (I've only skimmed the code so I might be missing something)

**Comment by aatchison** [comment] 2017-07-05 15:02
Apparently there is also an issue with the git checkout being dirty from the creation of .pyc files in the repo.

**Comment by penrods** [comment] 2017-10-26 22:15
I don't believe this is an issue anymore.  Can we close it?

**Comment by nealmcb** [comment] 2017-10-26 22:44
Sorry, but I can't help test right now.

**Comment by penrods** [comment] 2017-10-28 08:37
No worries, but as I'm certain this has been fixed I'm going to go ahead and close it out.

**Closed by penrods** 2017-10-28 08:37 UTC
