### ISSUE TITLE
timer skill tries to access ttyAMA0

### ISSUE THREAD

**Issue by zachwelch** [MycroftAI/mycroft-core#1437] opened 2018-02-22 17:52 UTC
# Context
Ubuntu 16.04
latest `dev` branch (0.9.17)

# Observation

When setting a timer, something in the system tries to access `/dev/ttyAMA0`, resulting in the following string of messages in the mycroft-voice.log file:
```
/bin/sh: 1: cannot create /dev/ttyAMA0: Permission denied                        
```
# Steps To Reproduce

"Hey Mycroft, Set a timer for one minute"

# Observed Result

The CLI shows the mycroft-voice.log filling with lines like the following:
```
/bin/sh: 1: cannot create /dev/ttyAMA0: Permission denied                        
```
# Expected Result

The `/dev/ttyAMA0` device should not be accessed on desktop systems.

**Comment by forslund** [comment] 2018-03-11 07:50
This is technically not a core issue, the problem is within the timer skill. I've opened a pull request which should handle this: https://github.com/MycroftAI/mycroft-timer/pull/11

**Comment by forslund** [comment] 2018-04-10 11:35
This should be resolved in the timer skill now. Closing this one. If the problem persists please reopen the issue.

**Closed by forslund** 2018-04-10 11:35 UTC
