### ISSUE TITLE
When Starting Mycroft via Command line, it constantly wants the Sudo password to reset the permissions on /opt/mycroft/skills directory

### ISSUE THREAD

**Issue by trekjunky** [MycroftAI/mycroft-core#2129] opened 2019-05-22 01:22 UTC
# How to submit an Issue to a Mycroft repository

When submitting an Issue to a Mycroft repository, please follow these guidelines to help us help you. 

## Be clear about the software, hardware and version you are running
****************************************************************************************
 check version                                                                                                                                                              
 >> I am running mycroft-core version 19 oh 2, release 7                                                                                                                    
 >> You are on the latest version.

I have installed Mycroft on OpenSuSE 15
AMD 8 core 64 bit processor
16 Gig RAM

My problem. When I launch ./start-myrcroft.sh all and ./start-mycroft.sh cli, each time and every time it asks for the sudo password to reset the permissions of /opt/mycroft/skills directory. the single script: ./start-mycroft.sh calls other scripts which act on resetting the permissions on the skills directory. I don't know which one or I would remove that call. Please help! I'm sick of the sudo password.

Changing ownership of /opt/mycroft to user: trekjunky with group: users
[sudo] password for root: 
all 5 logs are zipped up in the file below.
[mycroft.tar.gz](https://github.com/MycroftAI/mycroft-core/files/3205135/mycroft.tar.gz)

*******************************************************************************************

**Comment by krisgesling** [comment] 2019-05-23 06:24
Hi Trekjunky,

I had a look at this and think I've found the cause. I've submitted a fix that you'll see linked just above but this won't get pushed out to devices running stable for another two weeks. If you're running dev with autoupdates it will be included as soon as it's been reviewed by the team. Otherwise you can grab the new version of `~/mycroft-core/scripts/prepare-msm.sh` from [my fork](https://github.com/krisgesling/mycroft-core/blob/245458fa866a62cf671fa54bdcf12ba6291c671b/scripts/prepare-msm.sh), or modify the file locally and it should stop prompting you for the sudo password each time.

Essentially the permissions were set correctly but there was a small bug when testing if those permissions were correct. The existing version doesn't prompt on many machines because lots of people have their username and usergroup called the same thing. I'm assuming others have experienced the behaviour that you have and just assumed it's normal.

Thanks for flagging it and helping us improve Mycroft-core :slightly_smiling_face:

**Closed** 2019-05-23 07:57 UTC

**Comment by trekjunky** [comment] 2019-05-24 00:52
I copied your fork into my copy of prepare-msm.sh and it worked YAYAYAYAYAYAYAYAYAYA
Thanks so much!!!!!!!!!!
