### ISSUE TITLE
Wake up word is not recognized

### ISSUE THREAD

**Issue by mexican1973** [MycroftAI/mycroft-core#2445] opened 2019-12-31 02:01 UTC
Hi all.
I am using picroft and the respeaker mic array.
It recognizes fine "Hey mycroft" but not at all "Wake up".
Very annoying. How can I get it to work.
It reacts when saying "Wake up" since I see it is trying to establish an HTTP connection:
api.mycroft.ai ... get device settings and location. It keeps repeating it but it doesnt come back online. 
I think the wake up word somehow is not working.

**Comment by forslund** [comment] 2019-12-31 14:03
Also just to make sure, it's "Hey Mycroft" followed by "wake up"

**Comment by mexican1973** [comment] 2019-12-31 14:06
Yes. I always say "Hey mycroft wake up" but no reaction.

**Comment by forslund** [comment] 2019-12-31 14:17
Great, just wanted to make sure it wasn't a simple thing like that :)

**Comment by krisgesling** [comment] 2020-02-04 07:08
Hey @mexican1973, have you had any further luck on this? 

I just gave it a test on my Picroft and found it challenging to get it to recognise "wake up" as well. One thing to be aware of is that because Picroft's are generally a little slower, you do need to wait between the "Hey Mycroft" and the "wake up".

If you have the CLI open you should see that when you say "Hey Mycroft", you should see:
> INFO     |   713 | __main__:handle_record_begin:37 | Begin Recording...

this is local only recording to evaluate if the sound contains "wake up". After a short time you'll then see:
>  INFO     |   713 | __main__:handle_record_end:43 | End Recording...

And if you successfully wake Mycroft up: 
>  INFO     |   713 | __main__:handle_awoken:54 | Listener is now Awake:

If you're still seeing this issue, can you confirm that the "Hey Mycroft" is triggering the microphone to begin recording?

**Comment by forslund** [comment] 2020-05-06 08:36
Hi, since there been no communication here in a while and I can't reproduce the problem I'm closing this issue. if it's still a problem for you please re-open this issue. Thanks

**Closed by forslund** 2020-05-06 08:36 UTC
