### ISSUE TITLE
Arithmetic sums are recognised but reported weirdly

### ISSUE THREAD

**Issue by stuartlangridge** [MycroftAI/mycroft-core#28] opened 2016-05-22 23:22 UTC
"Hey Mycroft, what's two plus two?"

    2016-05-23 00:17:57,332 - SpeechClient - INFO - Utterance: [u'whats 2 plus 2']
    2016-05-23 00:17:57,341 - METRICS - DEBUG - {"attributes": {"version": "dev-9aa9f47", "utterances": ["whats 2 plus 2"]}, "levels": {}, "timers": {"mycroft.stt.remote.time_s": [1.7695190906524658], "mycroft.cerberus.proxy.client.time_s": [1.7695190906524658], "mycroft.recognizer.extractor.time_s": [0.07558488845825195], "mycroft.recognizer.audio.length_s": [2.816], "mycroft.recognizer.audio_extracted.length_s": [0.95525, 1.89575], "mycroft.stt.local.time_s": [0.017687082290649414, 0.008194208145141602, 0.003365039825439453, 0.0054209232330322266, 0.007082939147949219, 0.006096839904785156, 0.006500959396362305, 0.007088899612426758, 0.004624128341674805, 0.006964921951293945, 0.005579948425292969, 0.004889965057373047, 0.00451207160949707, 0.004775047302246094]}, "counters": {}}
    2016-05-23 00:17:57,343 - SpeechClient - INFO - Speak: I am searching for whats 2 plus 2
    2016-05-23 00:18:00,693 - SpeechClient - INFO - Speak: foot×2+2 feet is 4 feet

I never mentioned "foot"...

**Comment by Wolfgange3311999** [comment] 2016-05-22 23:26
I believe at the moment it goes through Wolfram Alpha. If I'm not mistaken then we need some sort of MathSkill.

**Comment by stuartlangridge** [comment] 2016-05-22 23:28
Sure, but Wolfram Alpha knows the right answer here -- http://www.wolframalpha.com/input/?i=2+plus+2 -- which suggests that it's a problem in how it's being asked?

**Comment by Wolfgange3311999** [comment] 2016-05-23 02:58
Hmm, that's strange. It gets exactly the same result as if the query were [`ft 2 plus 2`][1].

[1]:http://www.wolframalpha.com/input/?i=ft+2+plus+2

**Comment by Wolfgange3311999** [comment] 2016-05-23 03:13
@stuartlangridge Can you try reproducing the problem with [a debugged version I just made](https://github.com/Wolfgange3311999/mycroft-core)? I'm still in the progress of transitioning OSs and I've yet to get Mycroft running on it.

**Comment by stuartlangridge** [comment] 2016-05-23 08:41
I now get "I don't understand your request", strangely. (Note: I have changed version of mycroft core to debug a different issue.)

    2016-05-23 09:39:26,164 - RecognizerWrapper - INFO - STT JSON: {"alternative": [{"transcript": "what's 2+2"}, {"transcript": "what's 2 + 2"}, {"transcript": "what's two plus two"}, {"transcript": "whats 2 + 2"}, {"transcript": "what's TwoPlusTwo"}], "final": true}
    2016-05-23 09:39:26,164 - mycroft.client.speech.listener - DEBUG - STT: what's 2+2
    2016-05-23 09:39:26,165 - SpeechClient - INFO - Utterance: [u"what's 2+2"]
    2016-05-23 09:39:26,172 - SpeechClient - INFO - Speak: I am searching for unparsed utterance what's 2+2
    2016-05-23 09:39:26,175 - METRICS - DEBUG - {"attributes": {"version": "dev-b19142d", "utterances": ["what's 2+2"]}, "levels": {}, "timers": {"mycroft.stt.remote.time_s": [1.5301010608673096], "mycroft.cerberus.proxy.client.time_s": [1.5301010608673096], "mycroft.recognizer.audio.length_s": [2.1763125]}, "counters": {}}
    2016-05-23 09:39:29,884 - SpeechClient - INFO - Speak: Query:what's 2+2
    2016-05-23 09:39:32,098 - SpeechClient - INFO - Speak: Sorry, I don't understand your request.

**Comment by ryanleesipes** [comment] 2016-05-23 11:26
Yes, makes sense. In that version Wolfram is broken.

On Mon, May 23, 2016, 3:41 AM Stuart Langridge <notifications@github.com>
wrote:

> I now get "I don't understand your request", strangely. (Note: I have
> changed version of mycroft core to debug a different issue.)
>
> 2016-05-23 09:39:26,164 - RecognizerWrapper - INFO - STT JSON: {"alternative": [{"transcript": "what's 2+2"}, {"transcript": "what's 2 + 2"}, {"transcript": "what's two plus two"}, {"transcript": "whats 2 + 2"}, {"transcript": "what's TwoPlusTwo"}], "final": true}
> 2016-05-23 09:39:26,164 - mycroft.client.speech.listener - DEBUG - STT: what's 2+2
> 2016-05-23 09:39:26,165 - SpeechClient - INFO - Utterance: [u"what's 2+2"]
> 2016-05-23 09:39:26,172 - SpeechClient - INFO - Speak: I am searching for unparsed utterance what's 2+2
> 2016-05-23 09:39:26,175 - METRICS - DEBUG - {"attributes": {"version": "dev-b19142d", "utterances": ["what's 2+2"]}, "levels": {}, "timers": {"mycroft.stt.remote.time_s": [1.5301010608673096], "mycroft.cerberus.proxy.client.time_s": [1.5301010608673096], "mycroft.recognizer.audio.length_s": [2.1763125]}, "counters": {}}
> 2016-05-23 09:39:29,884 - SpeechClient - INFO - Speak: Query:what's 2+2
> 2016-05-23 09:39:32,098 - SpeechClient - INFO - Speak: Sorry, I don't understand your request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MycroftAI/mycroft-core/issues/28#issuecomment-220920539>
>
-- 
Ryan Sipes
CTO, Mycroft A.I.
https://mycroft.ai
785-979-6091

**Comment by ryanleesipes** [comment] 2016-05-23 23:28
Is it passing along " <- quotes? Therefore implying feet, like:
2"

**Comment by Wolfgange3311999** [comment] 2016-05-24 22:16
So, Mycroft sends the following query to Cerberus:
GET /wolframalpha/v2/query?input=what%27s+2%2B2 HTTP/1.1

Which evaluates to a search for `what's 2+2`. This means that cerberus must be appending a single quotation mark to the end. since [`what's 2+2'`](https://www.wolframalpha.com/input/?i=what%27s+2%2B2%27) causes the same problem.

**Comment by clusterfudge** [comment] 2016-05-24 23:55
Sorry the cerberus stuff isn't OSS yet, we had some keys dropped into the repo on accident and we're still trying to decide between cleanup, rotating keys, or snapshotting the repo. Hopefully we'll get to it this week. I'm inlining the cerberus code for the wolfram|alpha hander, and I don't see anything obviously wrong with it. I will, however, verify the outbound request this evening.

```
from urllib import urlencode

import tornado.gen
import tornado.web
from tornado.httpclient import HTTPRequest

from mycroft.cerberus.handlers.proxies import CerberusAuthProxyBase

ROOT_API_URL = 'http://api.wolframalpha.com/v2/query'
__author__ = 'seanfitz'


class WolframAlphaProxy(CerberusAuthProxyBase):
    @tornado.web.asynchronous
    @tornado.gen.coroutine
    def get(self, *args, **kwargs):
        access_key = str(self.settings.get('secrets', {}).get('wolfram_api_key'))
        params = self.request.query_arguments
        params['appid'] = access_key
        param_str = urlencode(params)

        # TODO: Implement caching on server
        request = HTTPRequest(ROOT_API_URL + "?" + param_str)
        response = yield self.fetch_coroutine(request)
        self.set_status(200)
        self.set_header("Content-Type", "text/xml")
        self.write(response.body)
```

**Comment by ryanleesipes** [comment] 2016-05-31 17:46
Assigning @jdorleans to review.

**Comment by ryanleesipes** [comment] 2016-06-05 03:17
This is finally fixed by a change made in the proxy service. However, some queries that hit Wolfram are still not processed correctly. That problem is being trailed in #63

**Closed by ryanleesipes** 2016-06-05 03:17 UTC
Labels: bug
