### ISSUE TITLE
Unable to install on latest Ubuntu

### ISSUE THREAD

**Issue by metasoarous** [MycroftAI/mycroft-core#2511] opened 2020-03-24 21:03 UTC
Hello! Thanks for your time :-)

## software, hardware and version

* master pull of the mycroft-core codebase

## steps that we can use to replicate the Issue

For example: 

1. Clone the repo to a machine running the latest version of ubuntu
2. Try to install/run the program with `dev_setup.sh` or `start-microft.sh`
3. Wait for a while during compilation, which ultimately fails

## Be as specific as possible about the expected condition, and the deviation from expected condition. 

I expect the application to be able to build and start, but it's failing to do so.

## Provide log files or other output to help us see the error

When it finally fails, the last thing I get is:

```
  CC       src/audio/libttsmimic_la-auclient.lo
  CC       src/audio/libttsmimic_la-au_command.lo
  CC       src/audio/libttsmimic_la-audio.lo
  CC       src/audio/libttsmimic_la-au_none.lo
  CCLD     libttsmimic.la
  CCLD     libttsmimic_lang_usenglish.la
  CCLD     libttsmimic_lang_cmu_grapheme_lang.la
  CCLD     libttsmimic_lang_cmu_indic_lang.la
  CCLD     libttsmimic_lang_cmulex.la
  CCLD     libttsmimic_lang_cmu_grapheme_lex.la
  CCLD     libttsmimic_lang_cmu_us_kal.la
  CCLD     libttsmimic_lang_cmu_time_awb.la
  CCLD     libttsmimic_lang_cmu_us_kal16.la
  CCLD     libttsmimic_lang_cmu_us_awb.la
  CCLD     libttsmimic_lang_cmu_us_rms.la
  CCLD     libttsmimic_lang_cmu_us_slt.la
  CCLD     compile_regexes
/usr/bin/ld: warning: libicui18n.so.64, needed by ./.libs/libttsmimic.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.64, needed by ./.libs/libttsmimic.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_hw_params_any'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_hw_params_sizeof'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_hw_params_set_channels'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_drop'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_writei'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `utext_openUTF8_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_close'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `u_errorName_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_state'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_hw_params'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `ucasemap_utf8ToLower_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_drain'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_config_update_free_global'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `ucasemap_open_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `ucasemap_utf8ToUpper_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_hw_params_set_format'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `uregex_close_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `uregex_setUText_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `uregex_matches_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_delay'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_strerror'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `uregex_openC_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_hw_params_set_access'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_wait'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_open'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_hw_params_set_rate'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_resume'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `snd_pcm_prepare'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `ucasemap_close_64'
/usr/bin/ld: ./.libs/libttsmimic.so: undefined reference to `uregex_reset_64'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:2705: compile_regexes] Error 1
make[1]: *** Waiting for unfinished jobs....
```

Thanks for your time!

**Comment by ChanceNCounter** [comment] 2020-03-24 22:12
Can you clarify which Ubuntu edition you mean? They've got 18.04 LTS, 19.10, and devel going.

**Comment by metasoarous** [comment] 2020-03-24 22:29
I'm on 19.10.

**Comment by krisgesling** [comment] 2020-03-25 03:10
A temporary workaround would be to skip the Mimic build using the `-sm` flag:
```
cd mycroft-core
./dev_setup.sh -sm
```

**Comment by ChanceNCounter** [comment] 2020-03-25 03:15
I don't really understand the packaging and deps side of things, but it looks like 19.10 has libicu63, and the above is looking for v64.

**Comment by forslund** [comment] 2020-03-25 11:11
Is @ChanceNCounter pkg-config/autotools is somehow suggesting to link against libicui18n.so.64 but that can't be found by the linker.

I'm going to reinstall my 19.10 VM and see if I can replicate the issue.

**Comment by forslund** [comment] 2020-03-25 14:12
I couldn't reproduce this on a fresh install :/

For the time being you can follow the advice by @krisgesling, pair the device without audio and then select the American male voice for the device after pairing.

Alternatively you can try out an unofficial repo with mimic: https://forslund.github.io/mycroft-desktop-repo/

**Comment by forslund** [comment] 2020-04-24 20:51
Hi @metasoarous, did you get any further on this? Do you still have the issue?

**Comment by forslund** [comment] 2020-04-27 08:54
Hi there, since there's been no communication for a while I'll close this issue. If you still have the problem feel free to reopen it.

**Closed by forslund** 2020-04-27 08:54 UTC
