### ISSUE TITLE
Strange Skill regex behaviour

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-core#2294] opened 2019-09-09 02:10 UTC
Interested in any comments or hypotheses on this one...

It was flagged that some utterances like "tell me about the royal bank of canada" were not receiving any response from Mycroft. So first stop was to investigate the Skill itself.

1. With the existing Skills regex, the Article Title is extracted correctly and returns a confidence of 0.375 however the intent does not seem to be triggered. 
2. While playing around, [adding an additional regex line](https://github.com/krisgesling/skill-wiki/tree/gez/fix-long-match):
  `.*(wiki|for|about|wikipedia)(?! (for|about)) the (?P<ArticleTitle>.+)`
  correctly triggered the intent despite it now returning a lower confidence of 0.1875.
     - Doing this as a one liner: 
  `.*(wiki|for|about|wikipedia)(?! (for|about))( the|) (?P<ArticleTitle>.+)`
  extracted `ArticleTitle` as "the" instead of "royal bank of canada"
3. Reverting the regex back to the original single line now matches the utterance and triggers the intent correctly.

So I'm presuming that it's something in the regex registration or caching, but thought I'd seek advice before diving too deep into the rabbit hole.

**Comment by forslund** [comment] 2019-09-09 05:30
I think the issue is that we are detaching intents and not keywords.

In the beginning the keywords were shared across skills so I guess that's why they aren't removed. Nowadays we tag each keyword to be skill specific so we should be able to remove them as well...

**Comment by forslund** [comment] 2024-09-08 08:34
Closing Issue since we're archiving the repo

**Closed by forslund** 2024-09-08 08:34 UTC
