### ISSUE TITLE
Installation crash (/libttsmimic.la' is not a valid libtool archive)

### ISSUE THREAD

**Issue by Tony450** [MycroftAI/mycroft-core#3144] opened 2022-12-08 19:48 UTC
Hello everyone,

I have problems with Mycroft (latest version) software installation on Linux (Kali distro). When I run “./dev_setup.sh” the execution of the script stops and I get the message “/libttsmimic.la’ is not a valid libtool archive”. The screenshot is on ![unnamed](https://user-images.githubusercontent.com/58591705/206552801-57dcecec-0145-491c-8a52-ca35842ef358.png).

I have researched a lot on the Internet but I haven’t found any solution for this. I have read in a few posts that some other people have had the same issue but nobody hasn’t answered them. I have tried to remove the environment and rebuild it again and the same error occurs.

Also, I have noticed that the software is somehow partially installed on my system. I say that since I can run some main commands such as “start-mycroft.sh all”, etc. However, if I run “start-mycroft.sh cli” an error displays saying that a python library is not installed, then I install it manually and I get another error message saying that another package is not installed (this never ends, I have associated this behaviour to the fact that the program is not completely installed).

I would be grateful if someone could help me with this problem, the software really appeals to me and I need it to advance with my master thesis.

Regards.

**Comment by krisgesling** [comment] 2022-12-09 21:35
Hi Tony, 

I don't have any immediate solution to addressing Mimic1 builds given the error you've posted. However you can run `./dev_setup.sh` with a `-sm` flag to skip the build of Mimic 1 altogether. If you're after local-only TTS our new Mimic 3 is a much better option, we just haven't got that in the default build script yet.

More on Mimic 3 here:
https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-tts/mimic-3

I'm going to leave this ticket open in case others hit the same thing, however it's not something that we'll be prioritizing at the moment.

**Comment by krisgesling** [comment] 2022-12-09 21:39
Actually this is a duplicate of #3115 so will close this but keep it linked for reference.

**Closed as completed by krisgesling** 2022-12-09 21:39 UTC
