### ISSUE TITLE
the installation is not working on mint, i have the same problem like in the other posts here

### ISSUE THREAD

**Issue by Z3r0ut** [MycroftAI/mycroft-core#2239] opened 2019-07-29 23:29 UTC
the installation is not working on mint, i have the same problem like in the other posts here
im reposting it because i didnt see a fix for this in these posts.. Pls help me..

**Comment by krisgesling** [comment] 2019-07-30 03:08
Hi Z3r0ut, I'm closing this as it seems to be a duplicate of the problems described in #2207

**Closed by krisgesling** 2019-07-30 03:08 UTC

**Comment by forslund** [comment] 2019-08-02 05:15
@Z3r0ut just letting you know that the fix for Mint supplied by @fermulator has now been merged. Feel free to give it a try!
In your mycroft-core directory run
```
git checkout dev
git pull
```

To pull down the latest changes.
