### ISSUE TITLE
Read timeout when asking settings to home.mycroft.ai (skills not appearing on home.mycroft.ai)

### ISSUE THREAD

**Issue by edaubert** [MycroftAI/mycroft-core#1382] opened 2018-01-26 15:48 UTC
With the master branch on https://github.com/MycroftAI/mycroft-core/commit/02eb1b8277d06c61a2448a6a9e2767f7cb1cc54a, the skills can't synchronized there settings with home.mycroft.ai.

Here is the kind of log for the weather skill
```
15:43:08.673 - mycroft.skills.settings:_request_my_settings:419 - INFO - getting skill settings from server for WeatherSkill
15:43:08.674 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
15:43:09.252 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/55b86889-3b3c-4744-9f8f-f82ae559ee31/skill HTTP/1.1" 200 2
15:43:09.254 - mycroft.skills.settings:_upload_meta:278 - INFO - sending settingsmeta.json for WeatherSkill to servers
15:43:09.255 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
15:43:24.637 - mycroft.skills.settings:_send_settings_meta:195 - ERROR - HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)
15:43:24.638 - mycroft.skills.settings:_save_hash:321 - INFO - saving hash skill-weather-b1f3a557fbec474e19f38c07975987e7
```

Here is the kind of log I get for my skill:
```
15:44:06.624 - mycroft.skills.settings:_request_my_settings:419 - INFO - getting skill settings from server for SpotifySkill
15:44:06.625 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
15:44:07.589 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/55b86889-3b3c-4744-9f8f-f82ae559ee31/skill HTTP/1.1" 200 2
15:44:07.594 - mycroft.skills.settings:_upload_meta:278 - INFO - sending settingsmeta.json for SpotifySkill to servers
15:44:07.597 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
15:44:23.116 - mycroft.skills.settings:_send_settings_meta:195 - ERROR - HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)
15:44:23.117 - mycroft.skills.settings:_save_hash:321 - INFO - saving hash spotify-cli-skill-9a496ab2d89cc4d044c2e2dfa4345cc2
```

For the `spotify-skill` available here: https://gitlab.com/my-reactivity/spotify-cli-skill
we should see on https://home.mycroft.ai, something about Client token and Secret token.

Here is the settingsmeta.json:
```
{
    "name": "Spotify",
    "skillMetadata": {
        "sections": [
            {
                "name": "App authentication",
                "fields": [
                    {
                        "type": "label",
                        "label": "Go to <a href=\"https://beta.developer.spotify.com/dashboard/applications\">Spotify developer dashboard</a> to get create an app and get client ID and Secret token.<br/><strong>Once saved</strong>, you need to open a browser to <a href=\"http://localhost:8998\">http://mycroft.ip:8998</a> to complete the authentication."
                    },
                    {
                        "name": "SP_ID",
                        "type": "text",
                        "label": "Client ID",
                        "value": ""
                    },
                    {
                        "name": "SP_SECRET",
                        "type": "password",
                        "label": "Secret Token",
                        "value": ""
                    }
                ]
            }
        ]
    }
}
```

I am still developing it so the skill may not work correctly but I already saw the parameters on home.mycroft.ai for a previous version I was testing.

Previously I already saw this kind of logs but just one or two times for the weather skill not mine.

**Comment by Mn0491** [comment] 2018-01-26 17:11
Currently working on this bug! thank you for reporting @edaubert

**Comment by AddoSolutions** [comment] 2018-01-26 17:49
I am having the same issue.  Let me know if I can add anything helpful to debugging this.

**Comment by Mn0491** [comment] 2018-01-26 20:54
@AddoSolutions are you on our mattermost chat? I'd love to ping you to see if we can get to the bottom of this. My username on there is micahel-mycroft if you'd like want to reach out

**Comment by Mn0491** [comment] 2018-01-26 22:36
If anyone is experiencing this same problem, this is currently caused by deleting a device in home.mycroft.ai before deleting the skills attached to that device. What's going on is that the device is gone which makes the skill disappear but the skills still exist in our database. So that causes the timeout since the api endpoint thinks the skill already exists. A quick workaround (not necessarily a good one) is to delete your account and recreate another one. Sorry for the inconvenience, we are working on this and should have it fixed in the next few days.

**Comment by Mn0491** [comment] 2018-01-31 15:55
PR in progress to squash this bug https://github.com/MycroftAI/mycroft-core/pull/1397

**Comment by edaubert** [comment] 2018-02-01 16:56
Seems ok to me with the last dev version.
Even the weather settings are now available.

Thanks

**Comment by penrods** [comment] 2018-02-01 18:21
Excellent!  Closing this out.

**Closed by penrods** 2018-02-01 18:21 UTC

**Comment by penrods** [comment] 2018-02-01 18:23
NOTE: For anyone experience the issue with skills not appearing in home.mycroft.ai, PR https://github.com/MycroftAI/mycroft-core/pull/1397 has been merged and will be in today's release.
