### ISSUE TITLE
Mycroft Voice Error

### ISSUE THREAD

**Issue by r3dArch** [MycroftAI/mycroft-core#904] opened 2017-07-11 17:16 UTC
I finally got Mycroft installed and sort of working, I'm using the gnome shell extension and can type commands.  There are some things I need to fix, first is the voice.  When I attach the voice screen it is filled with
`2017-07-11 13:11:51,741 - mycroft.tts - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/will/mycroft-core/mycroft/tts/__init__.py", line 79, in run
    self.p = play_wav(data)
  File "/home/will/mycroft-core/mycroft/util/__init__.py", line 91, in play_wav
    return subprocess.Popen(play_wav_cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
over and over.  I think it has something to with Mycroft trying to output audio and that I'm missing a python module to do so.  I've never actually used python so I'm not sure how to fix this and cannot find anything online.

**Comment by MatthewScholefield** [comment] 2017-07-14 18:33
It looks like the problem is that `aplay` isn't installed. This is provided by `alsa-utils`. Make sure to run `./dev_setup_debian.sh` (or if you are not on Ubuntu, run the appropriate `./dev_setup_LINUXOS.sh`).

**Comment by forslund** [comment] 2018-01-10 08:20
Since this hasn't been touched on since July I'm closing this. If this is still an issue please reopen it.

**Closed by forslund** 2018-01-10 08:20 UTC
Labels: type: bug
