### ISSUE TITLE
Jenkins checks fail sometimes with no reason.

### ISSUE THREAD

**Issue by NoamDev** [MycroftAI/mycroft-core#2632] opened 2020-07-05 08:11 UTC
I noticed that Jenkins checks fail sometimes for no reason, after the next commit when they would re-run everything would normal back. Even the last commit [failed the checks](https://hudson.mycroft.team/blue/organizations/jenkins/mycroft-core/detail/dev/67/pipeline).
 It seems like it's a matter of timeout. Maybe the timeout should be increased?

**Comment by forslund** [comment] 2020-07-05 15:07
In my experience there are 3 major types of recurring random failures
- First test that is run never replies. @krisgesling is experimenting with a startup delay to see if it's the cause of things
- News and Singing errors out when checking for stop messages, this may be some timing issue or that there is something wonky with the test code we wrote causing the message to be missed. (or playback doesn't quite start?). I've been setting up some debugging for this but not quite gotten around to doing the actually digging.
- Alarm skill queries is misinterpreted as Timer queries. My theory on this is a training instability in Padatious (this kind of thing has been observed quite a while but has been very random and hard to predict) 

I've also seen some rare skill errors causing failures, once in skill-date-time and for a while the weather skill were failing close to midnight UTC due to some time conversion thing. (Think there's an issue in the weather skill repo)

**Comment by krisgesling** [comment] 2020-07-07 06:11
Yep, I am far too aware of this issue. Any extra attention on it is warmly welcomed!

There's also an issue in Weather looking at what the temperature is at a certain time. Haven't looked into yet but it may be a timezone issue.

**Comment by krisgesling** [comment] 2020-09-22 07:57
Hey there, the issues here are being tracked by other more specific tickets. So I'm closing this now.

**Closed by krisgesling** 2020-09-22 07:57 UTC
Labels: help wanted, type: bug
