### ISSUE TITLE
I cannot change temperature units in the Weather skill

### ISSUE THREAD

**Issue by JuliaC29** [MycroftAI/mycroft-core#1897] opened 2018-12-03 22:15 UTC
```
$ cd /opt/mycroft/skills/mycroft-weather.mycroftai
$ sudo vim settings.json

{"__mycroft_skill_firstrun": false, "units": "default"}
```
I changed "default" to "celsius" but "fahrenheit" is still coming out.

Does anyone have suggestions?

**Comment by penrods** [comment] 2018-12-03 22:21
If you look the the weather skill it uses "f" and "c", not "celsius" or "farenheit".

https://github.com/MycroftAI/skill-weather/blob/18.08/__init__.py#L553

**Comment by forslund** [comment] 2018-12-26 09:49
Closing this issue. I can't reproduce and it should probably be filed under the weather skill. If you feel this is incorrect feel free to open a new issue under the skill-weather repository.

**Closed by forslund** 2018-12-26 09:49 UTC
