### ISSUE TITLE
Mycroft's configuration: change the TTS from mimic to espeak does not work

### ISSUE THREAD

**Issue by yannick56** [MycroftAI/mycroft-core#1256] opened 2017-11-23 22:55 UTC
Hello,

I have installed espeak
and the command line with the french voice 
espeak -vfr+m1 "Ceci est un test"
works fine.

But in the file
/home/user/mycroft-core/mycroft/configuration/mycroft.conf

I change the TTS from 

  // Text to Speech parameters
  // Override: REMOTE
  "tts": {
    // Engine.  Options: "mimic", "google", "marytts", "fatts", "espeak", "spdsay"
     "module": "mimic",
     "mimic": {
      "voice": "ap"
     },
     "espeak": {
      "lang": "english-us",
       "voice": "m1"
     }
   },

TO
  
    "tts": {
    // Engine.  Options: "mimic", "google", "marytts", "fatts", "espeak", "spdsay"
    "module": "espeak",
    "espeak": {
     "lang": "fr",
      "voice": "m1"
    }
  },

It does not works.
Mycroft still use mimic TTS with the english voice.

Can you fix this problem ?

**Comment by forslund** [comment] 2017-11-24 07:42
I think the problem is that you're editing the default configuration and the default is overridden by the configuration on home.mycroft.ai

The resolution order is:
`.../mycroft-core/mycroft/configuration/mycroft.conf`
home.mycroft.ai
`/etc/mycroft/mycroft.conf`
`~/.mycroft/mycroft.conf`

So if you want to override you should in most cases use `~/.mycroft/mycroft.conf` (where  ~ is the users home directory)

I set the `~/.mycroft/mycroft.conf` to

```json
{
  "tts": {
    "module": "espeak",
    "espeak": {
      "lang": "fr",
      "voice": "m1"
    }
  }
}
```

And it uses espeak, not 100% it's the french voice since I have very little to test with. "bonjour" sounded like I'd expect it to.

You could also try selecting espeak in the advanced settings on home.mycroft.ai

Hope this helps.

**Comment by yannick56** [comment] 2017-11-24 13:03
@forslund 

> I set the ~/.mycroft/mycroft.conf to
> {
>  "tts": {
>    "module": "espeak",
>    "espeak": {
>      "lang": "fr",
>      "voice": "m1"
>    }
>  }
> }

It works !
Thank you.

**Comment by forslund** [comment] 2017-11-24 13:06
Great to hear! Closing this issue.

**Closed by forslund** 2017-11-24 13:06 UTC

**Comment by yannick56** [comment] 2017-11-24 13:08
@forslund

> The resolution order is:
> .../mycroft-core/mycroft/configuration/mycroft.conf
> home.mycroft.ai
> /etc/mycroft/mycroft.conf
> ~/.mycroft/mycroft.conf
> So if you want to override you should in most cases use ~/.mycroft/mycroft.conf (where ~ is the 
> users home directory)

Maybe the following files/URLs  need more information to explain this process (with examples ? )  :
https://github.com/MycroftAI/mycroft-core/blob/dev/README.md
https://docs.mycroft.ai/development/faq
https://docs.mycroft.ai/development/cheatsheet/ubuntu
https://docs.mycroft.ai/skills.and.features/config

**Comment by forslund** [comment] 2017-11-24 13:12
The last document mentions this but could probably be clearer. @KathyReid is reworking our documentation, I'll let her know about this so it'll be improved for the next version of the documentation
