### ISSUE TITLE
Mycroft requires registration

### ISSUE THREAD

**Issue by Toover** [MycroftAI/mycroft-core#2665] opened 2020-08-17 07:06 UTC
# Version
Running Ubuntu 18.04.5 LTS, after proper installation from Git master, commit 
1a089256e79e99fd835d7de288bace93506840cd (v20.2.4).

# Protocol
Run the commands from the readme to install it.
Installation goes well.
Run the bot with: `./start-mycroft.sh debug`.
Wait for initialization.

# Observed
The bot keeps on telling me to go to home.mycroft.ai to register my device, and repeats the code.
The robot does not understand that I do not want to register my device:
```
I don't want to register
>> I don't understand
```

# Expected
Registration is optional, and the bot can talk about it.

**Comment by el-tocino** [comment] 2020-08-17 08:04
You'd have to set up your own backend server to handle this.  Check out the personal-backend or selene repos for more.

**Comment by krisgesling** [comment] 2020-08-18 02:15
Hi Toover, as el-tocino alluded to this requires some manual setup process and is not something we are spending time on automating at the moment.

Thanks for posting your thoughts on it though. It's useful for us to know of the interest in it so we can plan future functionality, and it's a good suggestion to add some more information so that Mycroft can talk to the user about it.

**Comment by krisgesling** [comment] 2020-08-18 02:19
Have created a ticket in the Pairing Skill to add this info, so will close this issue as it's the intended behaviour for now.

**Closed by krisgesling** 2020-08-18 02:19 UTC
