### ISSUE TITLE
(ArchLinux only?) mycroft.sh wake word recognition is broken with screen.

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-core#507] opened 2017-02-10 21:58 UTC
Two users have now found out the hard way that mycroft.sh isn't working correctly on ArchLinux. I just confirmed that it works on Ubuntu 16.10. Could someone running Arch investigate this?

**Comment by rafamanzo** [comment] 2017-02-11 00:27
What are the steps to reproduce?

**Comment by aatchison** [comment] 2017-02-11 00:31
Well, try doing a developemnt setup with git.
Run the build_host_arch script. Then dev setup.
Running Mycroft with the start.sh method should work, while mycroft.sh will not (with speech at least, cli is fine.)

**Comment by rafamanzo** [comment] 2017-02-11 01:08
I had previously installed Mycroft's dependencies. So `./build_host_setup_arch.sh` skipped everything. `./dev_setup.sh` took some time compiling but finished with success.

The run `mycroft.sh start` and spoke "Hey Mycroft, what's your name?". And it was recognized and answered just fine.

So I couldn't reproduce this on both my desktop and notebook Arch installations. Maybe it is because my system was basically already setup for Mycroft before and is biased.

Would be nice if somebody else could try to reproduce.

**Comment by BoBeR182** [comment] 2017-04-28 23:10
Cloned git, ran ```./build_host_setup_arch.sh```, it skipped everything.
```./dev_setup.sh``` compiled ```mimic``` and ran fine.
```mycroft.sh start -d``` works but Microphone is not detected, no answers.
Using the gnome extension, mycroft will start listening on the wakeword, but never stops, and never responds.

**Comment by aatchison** [comment] 2017-04-28 23:12
I think that this is an issue with the screen script itself, and it only happens sometimes.
Try running with the `./start.sh` method instead and let me know if that works.

**Comment by forslund** [comment] 2018-01-10 07:07
I'm closing this since the screen script was removed in 07992b49d56129fbd246ffb1d2057488bedea1d4.

**Closed by forslund** 2018-01-10 07:07 UTC
