### ISSUE TITLE
Feature Request: Easily enable full backend to run on local server

### ISSUE THREAD

**Issue by mcmurphy8097234789** [MycroftAI/mycroft-core#1605] opened 2018-05-22 05:59 UTC
So I am a user that lives where the internet is unreliable. As a result, mycroft can be unreliable. I was wondering if it would be possible to enable an easy-to-install version of mycroft that enables the full backend (including speech and intent processing) to run on a powerful local server. This would mean that mycroft could still do tasks that are not reliant on the outside world, like making lists. I

This would also be a boon for privacy, something that mycroft is heavily marketing. Anyway, thanks for listening!

**Comment by heaven00** [comment] 2018-05-26 20:51
There is some conversation here https://community.mycroft.ai/t/self-hosted-server/1266/11 but I think we should document it better, how to set it up

**Comment by heaven00** [comment] 2018-05-26 21:01
@mcmurphy8097234789 I think the key is to make all the services required running locally and all of that can be setup using the configuration file https://github.com/MycroftAI/mycroft-core#using-mycroft-without-home

Will try to set this up and add more details

**Comment by el-tocino** [comment] 2018-06-01 02:45
See also #1569

**Comment by JarbasAl** [comment] 2018-06-28 01:29
https://github.com/JarbasAl/personal-mycroft-backend/

**Comment by anurag-g** [comment] 2018-10-20 18:40
@JarbasAl Could you please throw some light on what is exactly happening in the project mentioned above. How do I customize the backend? As of now, I can't sign in at the frontend (It keeps saying sign in failed). 
Also the settings.py file sets USE_DEEPSPEECH to FALSE. So which stt are we using? I am finding it quite difficult to integrate your project with mycroft-core.
It'll be mighty helpful if you could provide documentation on how to bypass Mycroft.home (essentially what your project aims to do).
Thanks

**Comment by flatsiedatsie** [comment] 2019-07-18 11:40
> As of now, I can't sign in at the frontend (It keeps saying sign in failed).

I had that too with the default setup. The problem is that the certificates aren't installed by default, and the process to generate them isn't run. The solution is to change this line in settings.py:
`#if not SSL_CERT or not SSL_KEY:`
to
`if not exists(SSL_CERT) or not exists(SSL_KEY):`
So it actually checks if the files exist. I've created a pull request for this.

Now that SSL works, I've run into another issue where [Mycroft doesn't seem to accept self-signed certificates](https://github.com/MycroftAI/personal-backend/issues/37).

**Comment by forslund** [comment] 2024-09-08 08:39
Closing Issue since we're archiving the repo

**Closed by forslund** 2024-09-08 08:39 UTC
Labels: Type: Enhancement - proposed, help wanted, Difficulty: hard
