### ISSUE TITLE
"tell me about" not working correctly 

### ISSUE THREAD

**Issue by Jcode11** [MycroftAI/mycroft-core#121] opened 2016-06-08 21:03 UTC
when you say tell me about cats , he repeats you back "about cats" which is is messing up his search cause he often times will include about and the key word

**Comment by ethanaward** [comment] 2016-06-09 17:14
When I say `Mycroft, tell me about cats`, this is what I get:
```
2016-06-09 12:08:42,869 - mycroft.client.speech.listener - DEBUG - STT: tell me about cats
2016-06-09 12:08:42,869 - SpeechClient - INFO - Utterance: [u'tell me about cats']
2016-06-09 12:08:42,878 - SpeechClient - INFO - Speak: All right, I am looking for cats
...
2016-06-09 12:08:45,893 - SpeechClient - INFO - Speak: The domestic cat  or the feral cat  is a small, typically furry, carnivorous mammal. They are often called house cats when kept as indoor pets or simply cats when there is no need to distinguish them from other felids and felines.
```

That seems to be working as intended. The problem comes when it is heard as `Mycroft, me about cats`. He then searches for `me about cats`, which doesn't return anything he currently understands. This is part of #63, with improving what Mycroft can understand from Wolfram queries. It's also related to actually recognizing the audio correctly, which is another issue we plan on addressing.

**Comment by ryanleesipes** [comment] 2016-06-13 20:17
Closing, but we should keep these kind of queries in mind as we move forward.

**Closed by ryanleesipes** 2016-06-13 20:17 UTC
Labels: bug
