### ISSUE TITLE
bash dev_setup.sh fails with package installation

### ISSUE THREAD

**Issue by brobostigon** [MycroftAI/mycroft-core#1576] opened 2018-05-10 17:15 UTC
I am running mycroft on ubuntu 18.04, that was git pull'ed on the 10th of may, and i am getting the following error when it gets to package installation.

~/mycroft-core$ bash dev_setup.sh
Installing packages...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-gobject-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-gobject-2-dev

E: Package 'python-gobject-dev' has no installation candidate

**Comment by n1x0nj4** [comment] 2018-05-11 13:35
#1358

**Comment by forslund** [comment] 2018-05-11 13:54
This seems to be a regression when we merged the python3 branch. Thanks for noticing, will push an update.

**Comment by brobostigon** [comment] 2018-05-11 13:57
not a problem, :)

**Comment by MatthewScholefield** [comment] 2018-05-21 23:53
Should be fixed now that the package references `python-gobject-2-dev` in the `dev` branch.

**Closed by MatthewScholefield** 2018-05-21 23:53 UTC
