### ISSUE TITLE
Make message parameter optional in skill API

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-core#993] opened 2017-08-16 17:12 UTC
There are a lot of instances where the message parameter on skill handlers is unnecessary. To simplify the API I propose we make the parameter optional so that this skill would still be valid:

```Python
from mycroft.skills.core import MycroftSkill
class HelloSkill(MycroftSkill):
    def __init__(self):
        MycroftSkill.__init__(self)

    def initialize(self):
        # ...
        self.register_intent(hi_intent, self.say_hi)
        self.register_intent_file(hi_person_intent, self.say_hi_to_person)

    def say_hi(self):  # <<< No message parameter
        self.speak('Hi')

    def say_hi_to_person(self, message):
        person = message.data['person']
        self.speak('Hello ' + person)
```

For reference, to check the number of parameters of a function use one of the snippets below.

Python 2:
```Python
from inspect import getargspec
num_params = len(getargspec(my_function).args)
```

Python 3:
```Python
from inspect import signature
num_params = len(signature(my_function).parameters)

**Comment by azie-ginanjar** [comment] 2017-08-21 08:25
Hi @MatthewScholefield,
I interested to contribute on this project. Do you mind if I take on this one?

**Comment by MatthewScholefield** [comment] 2017-08-21 14:56
@azie-ginanjar I'd be delighted :smile:. Let me know if you encounter any issues.

**Comment by azie-ginanjar** [comment] 2017-08-21 23:16
@MatthewScholefield ok then thanks. hope I could get started soon :)

**Comment by azie-ginanjar** [comment] 2017-08-22 12:49
@MatthewScholefield on current state is function like
        def say_hi(self):  # <<< No message parameter
               self.speak('Hi')
is invalid?
Sorry I think I am not really understand about this issue :grimacing:

**Comment by forslund** [comment] 2017-08-23 15:05
Hello @azie-ginanjar.

The issue is for the the intent handler methods
these are currently activated from the message bus and are expected to take a parameter called `Message` which is the data from the message bus.

Currently they have to look like this:

```python
    def say_hi_handler(self, message):
```

This is because the caller tries to pass a message (see core.py: https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/core.py#L324)

what @MatthewScholefield suggests is that the function is checked before it's called to see if it accepts a message parameter or not.

The tool Matthew suggests is `getargspec(func).args` which returns a list with the arguments the function `func` accepts.

This makes it possible to check how many arguments should be provided using something along the lines of

```python
if len(getargspec(handler).args) == 1:
    handler(message)
elif len(getargspec(handler).args) == 0:
    handler()
else:
    raise AppropriateError
```

(note I'm not sure about the if the `self` parameter will be counted or not so it could be 2 and 1 arguments instead of 1 and 0 in the if statement above)

**Comment by azie-ginanjar** [comment] 2017-08-24 03:42
Hello @forslund,

Thanks a lot for your explanation, it's really helpful.

**Comment by azie-ginanjar** [comment] 2017-08-24 04:32
PR submitted: #1015

**Comment by forslund** [comment] 2017-09-26 14:33
Closing as #1015 has been merged.

**Closed by forslund** 2017-09-26 14:33 UTC
Labels: contributor friendly, difficulty: easy, type: Code Improvements / Refactor
