### ISSUE TITLE
Mycroft Prompts User to go to Cerberus Twice

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core#103] opened 2016-06-05 03:30 UTC
When not registered, Mycroft prompts user to go to the Cerberus URL twice in a row.

**Comment by ethanaward** [comment] 2016-06-09 18:13
I did some debugging, and the issue is in listener.py. If you say mycroft's name relatively slowly when trying to pair, he gets two separate relatively long pieces of audio, and creates two stt runnables, each of which tries to connect to Cerberus and gives an error when they can't.

```
2016-06-09 13:07:24,843 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): cerberus.mycroft.ai
2016-06-09 13:07:24,846 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): cerberus.mycroft.ai
2016-06-09 13:07:25,076 - requests.packages.urllib3.connectionpool - DEBUG - "POST /stt/google_v2?language=en-US&version=dev-d856b11 HTTP/1.1" 401 75
2016-06-09 13:07:25,078 - mycroft.client.speech.listener - ERROR - AccessDenied from Cerberus proxy.
2016-06-09 13:07:25,078 - SpeechClient - INFO - Speak: Your device is not registered yet. To start pairing, login at cerberus dot mycroft dot A.I
2016-06-09 13:07:25,093 - requests.packages.urllib3.connectionpool - DEBUG - "POST /stt/google_v2?language=en-US&version=dev-d856b11 HTTP/1.1" 401 75
2016-06-09 13:07:25,095 - mycroft.client.speech.listener - ERROR - AccessDenied from Cerberus proxy.
2016-06-09 13:07:31,956 - mycroft.client.speech.listener - DEBUG - ['pair my device']
2016-06-09 13:07:31,956 - SpeechClient - INFO - Speak: Your device is not registered yet. To start pairing, login at cerberus dot mycroft dot A.I
2016-06-09 13:07:38,861 - mycroft.client.speech.listener - DEBUG - ['pair my device', 'pair my device']
2016-06-09 13:07:38,864 - SpeechClient - INFO - Utterance: ['pair my device', 'pair my device']
```

**Comment by ryanleesipes** [comment] 2016-06-13 20:30
I'm adding @Wolfgange3311999 to this ticket to help solve this once and for all.

**Comment by Wolfgange3311999** [comment] 2016-06-20 17:05
This has been resolved with the new listener since only one audio segment is sent to be parsed. However I will keep this in mind when making the new passive listener.

**Closed by Wolfgange3311999** 2016-06-20 17:05 UTC
Labels: bug
