### ISSUE TITLE
pyee error | exception calling callback for <Future at 0x737d75f0 state=finished raised KeyError>

### ISSUE THREAD

**Issue by Y0ngg4n** [MycroftAI/mycroft-core#2695] opened 2020-09-16 19:03 UTC
# How to submit an Issue to a Mycroft repository

When submitting an Issue to a Mycroft repository, please follow these guidelines to help us help you. 

## Be clear about the software, hardware and version you are running

For example: 

* I'm running Picroft
* With latest version
* With the standard Wake Word

## Try to provide steps that we can use to replicate the Issue

For example: 

1. Open mycroft cli
2. wait (it comes every ca. 30 seconds)

## Provide log files or other output to help us see the error
```20:00:14.407 | ERROR    |   949 | concurrent.futures | exception calling callback for <Future at 0x737d7b10 state=finished raised KeyError>Traceback (most recent call last):  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks    callback(self)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_executor.py", line 60, in _callback    self.emit('error', exc)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 111, in emit    self._emit_handle_potential_error(event, args[0] if args else None)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 83, in _emit_handle_potential_error    raise error  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run    result = self.fn(*self.args, **self.kwargs)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 121, in g    self.remove_listener(event, f)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 136, in remove_listener    self._events[event].pop(f)KeyError: <bound method MessageWaiter._handler of <mycroft.messagebus.client.client.MessageWaiter object at 0xb2e8fd90>> 20:00:14.408 | ERROR    |   949 | concurrent.futures | exception calling callback for <Future at 0x737d79d0 state=finished raised KeyError>Traceback (most recent call last):  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks    callback(self)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_executor.py", line 60, in _callback    self.emit('error', exc)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 111, in emit    self._emit_handle_potential_error(event, args[0] if args else None)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 83, in _emit_handle_potential_error    raise error  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run    result = self.fn(*self.args, **self.kwargs)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 121, in g    self.remove_listener(event, f)  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 136, in remove_listener    self._events[event].pop(f)KeyError: <bound method MessageWaiter._handler of <mycroft.messagebus.client.client.MessageWaiter object at 0x7514b7b0>>```

![image](https://user-images.githubusercontent.com/30302975/93380706-e2455e80-f85f-11ea-8395-c96aa26fbf14.png)

**Comment by forslund** [comment] 2020-09-16 20:09
Could you try to set the log level to debug by entering the cli command `:log level debug` to see if it gives any more info what it tries to do right be fore the error there?

It looks like an error shown when the `wait_for_response()` or `wait_for_message()` tries to remove a handler that's already been removed. Will see if I can provoke it to happening.

**Comment by Y0ngg4n** [comment] 2020-09-17 12:16
![Screen Capture_deepin-terminal_20200917141521](https://user-images.githubusercontent.com/30302975/93469168-67785400-f8f0-11ea-8925-80d32e26e33e.png)
![Screen Capture_deepin-terminal_20200917141536](https://user-images.githubusercontent.com/30302975/93469170-68a98100-f8f0-11ea-909f-560d64f1b1b2.png)
![Screen Capture_deepin-terminal_20200917141604](https://user-images.githubusercontent.com/30302975/93469172-69421780-f8f0-11ea-8827-ce0875a65cd6.png)

**Comment by Y0ngg4n** [comment] 2020-09-17 16:02
@forslund sorry :/

**Comment by j1nx** [comment] 2020-09-29 11:27
Just an idea here. If the user or some skill installs the "mycroft-messagebus-client" pip package, there is a pyee version conflict as the messagebus-client is still using pyee==5.0.1

https://github.com/MycroftAI/mycroft-messagebus-client/pull/4

I am seeing that when installing systemwide as --user option. Not sure if it also occurs within a venv. Perhaps it is related as it is about pyee.

**Comment by forslund** [comment] 2020-09-29 19:59
If that happens I do believe (after testing) the errors occurring would be ImportErrors since the ExecutorEventEmitter class isn't available.

**Comment by krisgesling** [comment] 2020-09-30 10:00
After some more probing and chatting with Ake, I think this might be the [`MessageBusClient.emitter.once`](https://github.com/MycroftAI/mycroft-core/blob/a5b7f55ae400da9d20e703ec6c8e5008be6853bd/mycroft/messagebus/client/client.py#L204) method attempting to pop the callback function off an event that has already been cleared. 

We still need to verify this and if true, perhaps ensure that each function registered is unique.

**Comment by forslund** [comment] 2020-10-05 07:25
So I did some testing and each function registered is unique. I think the issue here is non-fatal since the exception is catched and reported.

My tests makes me believe the issue is a race condition between the timeout (which removes the handler) and the pyee `once` automatic removal of the handler. This may be something that we need to report upstream to pyee...

I've seen the error myself randomly and added some extra logging to see if I can pinpoint where in mycroft's code it gets triggered. Somewhere in the skills process...

**Comment by forslund** [comment] 2020-10-07 05:37
I opened an issue upstream.

**Comment by forslund** [comment] 2020-10-08 21:08
Ok a fix to my theoretical observation has been merged in pyee and released as 8.1.0. I'll prepare a PR here and on Adapt to get the versions synced and we'll see if that resolves the issue. Otherwise there's some other issue as well :)

**Comment by forslund** [comment] 2021-04-25 19:35
Hi, I'm going to close this issue for now. The proposed update to resolved this has been accepted upstream and Mycroft has included it.

In addition the functionality handling this has been moved out from core into [mycroft-messagebus-client](https://github.com/MycroftAI/mycroft-messagebus-client/). If you're still seeing this issue please reopen the issue there.

**Closed** 2021-04-25 20:35 UTC
Labels: Difficulty: hard, Type: Bug - complex, help wanted
