### ISSUE TITLE
Failing to run on Python3.9

### ISSUE THREAD

**Issue by opensource-assist** [MycroftAI/mycroft-core#2456] opened 2020-01-18 04:30 UTC
While running [dev_setup.sh](https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh), this error message pops up:

```
Traceback (most recent call last):
  File "<stdin>", line 20649, in <module>
  File "<stdin>", line 197, in main
  File "<stdin>", line 82, in bootstrap
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmp0ga497z7/pip.zip/pip/_internal/__init__.py", line 20, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmp0ga497z7/pip.zip/pip/_vendor/urllib3/__init__.py", line 8, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmp0ga497z7/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 29, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmp0ga497z7/pip.zip/pip/_vendor/urllib3/connection.py", line 39, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmp0ga497z7/pip.zip/pip/_vendor/urllib3/util/__init__.py", line 3, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmp0ga497z7/pip.zip/pip/_vendor/urllib3/util/connection.py", line 3, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmp0ga497z7/pip.zip/pip/_vendor/urllib3/util/wait.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmp0ga497z7/pip.zip/pip/_vendor/urllib3/util/selectors.py", line 14, in <module>
    
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.9/collections/__init__.py)
Failed to set up virtualenv for mycroft, exiting setup.
```
Python 3.9.0a2+ on Debian Experimental

**Comment by ChanceNCounter** [comment] 2020-01-18 07:30
Looks like `Mapping` has moved. I _think_ this is an easy fix.

**Comment by ChanceNCounter** [comment] 2020-01-18 07:39
I stand further corrected. I seem to have tried to debug an older version of urllib3. I'm guessing it's urllib3.

The version I've got has every `Mapping` import in a try/catch block that falls back on the "new" (not so new) module.

**Comment by ChanceNCounter** [comment] 2020-01-18 07:44
[Yep](https://github.com/urllib3/urllib3/issues/1772). The problem is urllib3 descending from a version of Tornado that still has that old import.

It looks like they've merged a fix, but it hasn't found its way to PyPI.

**Comment by opensource-assist** [comment] 2020-01-18 11:08
@ChanceNCounter 
> Looks like `Mapping` has moved. I _think_ this is an easy fix.
> 
> edit: I stand corrected, it looks like it might be in a dependency. @opensource-assist is there more to the traceback?

No, that's all.

**Comment by forslund** [comment] 2020-01-18 11:35
I think for now it's a waiting game, you could try to change the requirements.txt to point to the github repo while experimenting. I suspect there might be additional issues in core itself as well.

I've just built the latest 3.9 alpha and will checkifor issues during the weekend

**Comment by forslund** [comment] 2020-01-19 15:44
Ok so the first issue was in the get_pip script used to install pip in the system. The nailed version of the script uses a 19.1 version of the script lacking some updates required to run on python3.9. Using PR #2458 I got it to complete the dev_setup.sh script without errors. Still need to test if anything will run...

**Closed** 2020-01-28 14:29 UTC
Labels: dependencies, platform: debian
