### ISSUE TITLE
Customized wake word broken in 0.8.22

### ISSUE THREAD

**Issue by smpickett** [MycroftAI/mycroft-core#1105] opened 2017-09-22 03:17 UTC
Customized wake words no longer work; the 'config' doesn't get configured with the wake word. See a debugging log below:
`2017-09-22 03:11:07,132 - mycroft.client.speech.listener - INFO - creating wake word engine`
`2017-09-22 03:11:07,133 - mycroft.client.speech.listener - INFO - ### phonemes HH EY . V IH K T AO R IY AH`
`2017-09-22 03:11:07,134 - mycroft.client.speech.listener - INFO - ### word hey victoria`
`2017-09-22 03:11:07,134 - mycroft.client.speech.listener - INFO - ### config {u'wake up': {u'threshold': 1e-20, u'phonemes': u'W EY K . AH P', u'module': u'pocketsphinx'}, u'hey mycroft': {u'threshold': 1e-90, u'phonemes': u'HH EY . M AY K R AO F T', u'module': u'pocketsphinx'}}`

`Traceback (most recent call last):
  File "/usr/local/bin/mycroft-speech-client", line 14, in <module>
    load_entry_point('mycroft-core==0.8.22', 'console_scripts', 'mycroft-speech-client')()`
`  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.22-py2.7.egg/mycroft/client/speech/main.py", line 140, in main
    loop = RecognizerLoop()`
`  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.22-py2.7.egg/mycroft/client/speech/listener.py", line 193, in __init__
    self._load_config()`
`  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.22-py2.7.egg/mycroft/client/speech/listener.py", line 211, in _load_config
    self.wakeword_recognizer = self.create_wake_word_recognizer()`
`  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.22-py2.7.egg/mycroft/client/speech/listener.py", line 230, in create_wake_word_recognizer
    LOG.info("### config {}".format(config[word]))`
`KeyError: u'hey victoria'`

**Comment by forslund** [comment] 2017-09-22 06:31
Thanks for reporting!

Does it revert to standard Hey Mycroft or does it silently crash?

**Comment by smpickett** [comment] 2017-09-22 14:11
It causes the mycroft-speech-service to fail to boot, so it is completely unresponsive. If the default is configured at home.mycroft.ai (with 'hey mycroft') then it works fine.

**Comment by smpickett** [comment] 2017-09-22 14:33
I just took a look at #1106 - I'm not sure if it will completely solve the problem as the 'config' variable didn't get initialized with the wakeword/phoneme pair (see the debug log above - it only had the defaults)

**Comment by forslund** [comment] 2017-09-23 11:49
I'll recheck the PR but I could change between `hey mycroft` and `hey victoria` without any issues.

**Comment by forslund** [comment] 2017-09-23 11:52
Are you changing the wakeword using mycroft or are you doing it locally with the config file?

**Comment by forslund** [comment] 2017-09-24 15:25
I've retried and changing the wake word using home.mycroft.ai works. I'll do a test changing the local config as well.

**Comment by smpickett** [comment] 2017-09-24 20:33
I just tried again back and forth. Same behaviour. What do you suggest to fix, or to help in debugging?

**Comment by forslund** [comment] 2017-09-24 21:06
Weird. I take it you're changing the wake word with via home.mycroft.ai using the branch for the PR then. I wonder what's different between our setups. Maybe you could print the config dict after line 223.

I believe you can work around this by creating the `~/.mycroft/mycroft.conf`

with

```json
{
  "listener": {
    "wake_word": "hey victoria"
  },
  "hotwords": {
    "hey victoria": {
        "module": "pocketsphinx",
        "phonemes": "HH EY . V IH K T AO R IY AH",
        "threshold": 1e-90
      }
  }
}
```

From the log you posted it reads as if the "hey victoria" hotword doesn't exist (which it expected only "hey mycroft" exists in the default config), the idea is that it should be overwritten by the settings from the web if they are missing. (the PR would create a dict if missing so should at least be part of the solution)

Will investigate more tomorrow morning.

**Comment by highjinx411** [comment] 2017-10-24 07:19
I don't think this is an issue with the exist.  There is something wrong with the create_dict in the hotword factory.. Something with the phonemes and the way home creates it.  He needs to upload his config file for the hotword.  It might be the web config isn't putting the  '.' after teh HH EY.. Which create_dict splits that string on '.'.  If the count between the phoneme groups and the keywords are different I think that is the crash..

**Comment by highjinx411** [comment] 2017-10-24 07:19
Not sure though. I reverted mine to hey mycroft and am still getting a crash.

**Comment by highjinx411** [comment] 2017-10-24 07:25
Oh I am commenting on something different... This issue was with his config file look at the log.  
2017-09-22 03:11:07,132 - mycroft.client.speech.listener - INFO - creating wake word engine
2017-09-22 03:11:07,133 - mycroft.client.speech.listener - INFO - ### phonemes HH EY . V IH K T AO R IY AH
2017-09-22 03:11:07,134 - mycroft.client.speech.listener - INFO - ### word hey victoria
2017-09-22 03:11:07,134 - mycroft.client.speech.listener - INFO - ### config {u'wake up': {u'threshold': 1e-20, u'phonemes': u'W EY K . AH P', u'module': u'pocketsphinx'}, u'hey mycroft': {u'threshold': 1e-90, u'phonemes': u'HH EY . M AY K R AO F T', u'module': u'pocketsphinx'}}

See how the file does u'hey mycroft' .  It should do "hotword"{"hey victoria" :{xxx}  }  the one he had in the log didn't have "hotword" which is referenced by the hotword factory so it crashed.

**Comment by forslund** [comment] 2017-10-24 07:27
The accessing a non-existing dict was an issue but was fixed. There's also been a couple of minor fixes the past weeks that may have improved this issue.

Personaly I've not been able to reproduce this for a while but that doesn't mean it's fixed...

**Comment by highjinx411** [comment] 2017-10-24 08:13
I have had something weird happen in that area.. I have a log file with lots of errors on initializing.

[mycroft-speech-client.log](https://github.com/MycroftAI/mycroft-core/files/1410021/mycroft-speech-client.log)

**Comment by highjinx411** [comment] 2017-10-24 08:15
{
"hotwords": {
    "hey mycroft": {
        "module": "pocketsphinx",
        "phonemes": "HH EY . M AY K R AO F T",
        "threshold": 1e-90
        },

    "wake up": {
        "module": "pocketsphinx",
        "phonemes": "W EY K . AH P",
        "threshold": 1e-20
        }
},
  "tts": {
    "mimic": {
      "path":"/usr/local/bin/mimic"
    }
  },
  "SkillInstallerSkill": {
    "path": "/usr/local/bin/msm"
  }
}

**Comment by forslund** [comment] 2017-10-24 13:49
Strange, what are your settings on home.mycroft.ai? (wakeword and phonemes are probably most relevant)

**Comment by highjinx411** [comment] 2017-10-31 20:16
My settings on home.mycroft.ai were the same.  wake word "hey mycroft" phonemes = "HH EY . MYCROFT"

**Comment by penrods** [comment] 2017-10-31 22:08
@highjinx411, can you post the contents of the cached web-config.  This is found at:  /opt/mycroft/web_config_cache.json

We have put some guard-rails on this lately, but perhaps there is still something missed that leads to a a crash.

**Comment by forslund** [comment] 2017-10-31 22:18
@highjinx411 I'm also curious about that file so if you dont post it here, could you kindly copy me aswell at ake.forslund@mycroft.ai or to ake-mycroft at the Mattermost chat.

Another thing, I assume there was some copy-past error in the phonemes you posted since they're not quite right. Should be "HH EY . M AY K R AO F T".

**Comment by forslund** [comment] 2018-04-10 11:36
I'm fairly certain this is working now and will close this issue. If the problem still occurs please reopen the issue.

**Closed by forslund** 2018-04-10 11:36 UTC
