### ISSUE TITLE
MYCROFT NOT WORKING ON KUBUNTU SHOWING ERROR OF WHILE INSTALLING PY YAML AND SHOWING ERROR WHEN I AM TRYING TO RUN

### ISSUE THREAD

**Issue by kingmehar** [MycroftAI/mycroft-core#3160] opened 2023-11-10 06:32 UTC
I am using Kubuntu 
To reproduce
Just follow the official guide and while installing you will get this error

WHEN INSTALLING
Error part of log:

```
Collecting PyYAML==5.4
  Using cached PyYAML-5.4.tar.gz (174 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/p/mycroft-core/.venv/bin/python3 /home/p/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpw67vzerf
       cwd: /tmp/pip-install-4626casl/PyYAML
  Complete output (68 lines):
  /tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!
  
          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.
  
          This deprecation is overdue, please update your project and remove deprecated
          calls to avoid build errors in the `future.`
  
          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************
  
  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/p/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/p/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/p/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 318, in run
      self.find_sources()
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
      mm.run()
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 548, in run
      self.add_defaults()
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 201, in get_source_files
    File "/tmp/pip-build-env-tbsgf4r2/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/p/mycroft-core/.venv/bin/python3 /home/p/mycroft-core/.venv/lib/python3.11/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpw67vzerf Check the logs for full command output.
Warning: Failed to install required dependencies. Continue? y/N
y

```

I IGNORED THE ERROR AND WENT AHEAD WITH THE INSTALLATION

After installing getting error:

```
Already up to date.
Starting all mycroft-core services
Initializing...
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting background service audio
Starting background service voice
Starting background service enclosure
Starting cli
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/p/mycroft-core/mycroft/__init__.py", line 17, in <module>
    from mycroft.api import Api
  File "/home/p/mycroft-core/mycroft/api/__init__.py", line 22, in <module>
    from mycroft.configuration import Configuration
  File "/home/p/mycroft-core/mycroft/configuration/__init__.py", line 15, in <module>
    from .config import Configuration, LocalConf, RemoteConf
  File "/home/p/mycroft-core/mycroft/configuration/config.py", line 24, in <module>
    import xdg.BaseDirectory
ModuleNotFoundError: No module named 'xdg'
p@p-hp:~/mycroft-core$ source venv-activate.sh
Entering Mycroft virtual environment.  Run 'mycroft-venv-deactivate' to exit

```
I Have tried installing manually but then it gives error for another package and then another package

```
(.venv) p@p-hp:~/mycroft-core$ pip install xdg
Collecting xdg
  Downloading xdg-6.0.0-py3-none-any.whl (3.9 kB)
Installing collected packages: xdg
Successfully installed xdg-6.0.0
```

**Comment by Semisuperman** [comment] 2023-11-12 04:45
I have the same issue installing on Ubuntu 22.04 via a git clone

**Comment by Deiiji** [comment] 2023-11-26 18:59
Hello, same with ubuntu 22.04 on rockship 3588 sbc and with Bookworm on rpi 4/8

**Comment by gujadin** [comment] 2023-12-24 00:58
The problem is linked to the version of the `PyYAML` python module.
To bypass this, you can allow a more recent version of the module in `requirements/requirements.txt` by changing `PyYAML==5.4` to `PyYAML>=5.4` (thus, it will install the v6.0.4 instead of the v5.4).

I don't know if this could create more unwanted issues with other systems but it works for me (Kubuntu 22.04).

**Comment by forslund** [comment] 2024-09-08 08:14
Closing PR since we're archiving the repo

**Closed as completed by forslund** 2024-09-08 08:14 UTC
Labels: bug
