### ISSUE TITLE
installation of skill confirmation doesn't work from CLI and in general is undocumented

### ISSUE THREAD

**Issue by fermulator** [MycroftAI/mycroft-core#2539] opened 2020-04-16 11:39 UTC
* I'm running Linux Mint 18.X
* `20.2.1`
* "Hey Mycroft" wake word, mostly defaults

## Try to provide steps that we can use to replicate the Issue

For example: 

1. As per https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/installing-new-skills
2. When a user tries to install a skill using the speaking "Hey mycroft, install <skill>", or the `msm install <skill>`, mycroft asks for confirmation but it is unclear how to confirm!

Example:
```
 msm install Dismissal                                                                skills.log, other                                                                 
 >> Confirming: Shall I install dismissal by ChanceNCounter.                          voice.log                                                                         
yes
>> Sorry, I didn't catch that.
 msm yes                                                                                                                                                                
 >> sorry ...
```

I _think_ there is a clear bug here ... how to confirm on the command line?
(I can hear my mycroft in the other room asking for confirmation but I'm not in there to confirm!)

or speak:
```
Hey Mycroft, install dismissal
>> Confirming: Shall I install dismissal by ChanceNCounter.
Yes
```

## Expected results

1. I expected the simple response of "yes" or "no" to constitute confirmation on the CLI (or to not be required at all if it was entered as a raw `msm` command)
2. If I typed "Hey Mycroft, install <skill", then typed "yes" or "hey mycroft, yes", that should constitute as confirmation.
2. I expect the documentation to reflect this requirement of confirmation and how to do it w/ examples

**Comment by forslund** [comment] 2020-04-16 13:25
Hi,

I can't reproduce this issue. I tried both voice and CLI without issue (Tested on Ubuntu 18.04 and Mark-1) (more than having to speak yes very clearly for it to be picked up by stt)

```
 install dismissal skill
 >> Confirming: Shall I install dismissal by ChanceNCounter.
yes
>> dismissal is now installed and ready for use
```

**Comment by krisgesling** [comment] 2020-04-16 13:34
With the MSM command, did you run this on your shell, not in the Mycroft CLI?

So it would look something like: 
```
kris@myComputer:~$ mycroft-msm install dismissal
```

**Comment by fermulator** [comment] 2020-04-17 12:36
I was running inside of the Mycroft CLI;

**Comment by fermulator** [comment] 2020-04-17 12:49
I see now;

so

1. The usage of `msm` is actually OUTSIDE the Mycroft CLI (this is actually stated in the docs kind of ... it references mycroft skills manager, which is a separate entity in of itself: https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/msm#using-mycroft-skills-manager-msm)
, this worked!

2. The ability for a user to TYPE the confirmation (for me) doesn't work at all.
```
  install auto-volume
>> auto volume has already been installed                                            DEBUG output                                                                      
 remove auto-volume                                                                   skills.log, other                                                                 
 >> Please rephrase your request.                                                     voice.log                                                                         
 uninstall auto-volume                                                                                                                                       --- 122.66 
 >> Confirming: Shall I remove auto volume by andlo.                                                                                                                    
 yes                                                                                                                                                                    
 >> Sorry, I didn't catch that.       
```

**Comment by fermulator** [comment] 2020-04-18 13:56
An important correction ... the CLI isn't accepting "yes" for ANY confirmation
```
 restart                                                                                                                                                                
 >> Confirming: Would you like me to restart now?                                                                                                                       
 yes                                                                                                                                                         --- 
 >> I'm sorry, I don't understand.                                                                                                                                      
```

**Comment by forslund** [comment] 2020-04-19 09:30
That sounds like something is quite broken...

A couple of clarifications:
- Are you running the latest dev branch or the latest master?
- Do you hear the listening ding before entering yes? (The converse handler that should catch the yes/no isn't registered until after the utterance is completely spoken by Mycroft)

**Comment by fermulator** [comment] 2020-04-22 00:52
Great questions.

I think there is a conversation problem; I _do not_ hear the "listen ding" for any sub-prompt from Mycroft.  Whether it is confirmation, or "sorry I didn't get that" type responses -- mycroft never re-opens the listener for a second time without the wake word.

**Comment by krisgesling** [comment] 2020-04-22 01:51
Yeah the default branch for this repository is dev as that's the branch people need to push changes to.

The installation script in `dev_setup.sh` asks which branch you want to run on when you first get setup and it then switches to the appropriate branch. 

That's interesting about the ding not playing on subsequent prompts. Is that the same if you say something like:
"Hey Mycroft *ding* set a timer"
M: "How long of a timer" *ding*
?

If you run the CLI interface `mycroft-cli-client` there will be green messages when the listener is active, these should coincide with the *dings*

**Comment by fermulator** [comment] 2020-04-22 12:09
I probably chose master because usually it means "stable", and "dev" means unstable ... for the sake of testing, I've checked out and pulled down dev branch now. There were a handful of changes/diffs.

Restart resulted in a bunch of new packages being installed
`libpulse-mainloop-glib0 libpulse0 libpulsedsp libsnapd-glib1 pulseaudio-module-bluetooth pulseaudio-module-x11` as well as all sorts of python pip pkg upgrades.

Re-entering the CLI:
```
 hey mycroft, install autovolume                                                                                                                                        
 >> Confirming: Shall I install auto volume by andlo.                                                                                                                   
 nevermind                                                                                                                                                   --- 396.25 
 >> Cancelled.    
```

works now! ;/  - so the master branch is super old or broken?

**Comment by forslund** [comment] 2020-04-22 12:16
Master is what is currently on devices (it's about a month old) and has been working well on those (for me at least). But we have found some theoretical issues with the converse system that has been fixed. It may be that you've been affected by one of those.

**Comment by fermulator** [comment] 2020-04-23 00:07
excellent;  all good then, (presumably mycroft has some sort of release/delivery cadence for merging dev into master for a release)

so all that's left on this ticket is a simple "improve the docs" PR; agreed? (if so I can whip up a PR)

**Comment by forslund** [comment] 2020-04-23 19:19
Sounds alright to me. Should I move this issue over to the documentation repo or should we close it here and open a separate one over there?

**Comment by fermulator** [comment] 2020-04-26 17:35
My system has started once again having conversation auto-listen problems again.  (no change to git and haven't restarted ...)

Maybe need to conduct some more explicit testing to get a feel for the problem ... I think we should close this ticket and fork/create new one(s) for the specific scope; (history of this one is a bit muddly)

**Comment by forslund** [comment] 2020-04-27 07:50
Ok, sounds good. Closing this one. Looking forward to your more detailed analysis, will also try to see if I can reproduce it.

**Closed by forslund** 2020-04-27 07:50 UTC

**Comment by fermulator** [comment] 2020-06-30 14:22
BTW: after transitioning to picroft, fresh install, this issue (in a reduced form) is still present;

```
 uninstall skill count                                                                                                                                                 
 >> Confirming: Shall I remove count by andlo.                                                                                                                         
 yes                                                                                                                                                          --- 54.00
 >> I don't understand.                                                                                                                                                
```
(you can't, from the CLI, simply "type like speak" to issue a command - certainly though the `msm` commands do work) - basically the "confirm" prompts don't seem to work via the CLI

, the default branch is `master`; when are we merging in the the `develop` fixes?
```
(.venv) pi@picroft:~/mycroft-core $ git status
On branch master
Your branch is up to date with 'origin/master'.
```
@forslund @krisgesling

**Comment by fermulator** [comment] 2020-06-30 14:23
PS: which ticket ended up existing to fix/update the docs? (or was that on me to submit and do a PR for? might've dropped the ball)

**Comment by krisgesling** [comment] 2020-07-03 06:06
Hey, when typing responses to a prompt you have to submit them while the listener is active, otherwise the system treats it as a new utterance. If you have the CLI active you should see the recording begin and end messages show in green. Can you check if this is the issue or if its failing even when submitted at a different time?

The default branch if you just clone the repository is dev because that's what developers will hopefully be using and it's the branch that any PR's should be made against. 

The setup script asks whether users want to use master or dev and switches appropriately. Master is the most stable and is a snapshot of dev at the last major release tag but should not be used for development.

If there are improvements to the main [documentation](https://mycroft-ai.gitbook.io/docs/) needed that is all hosted in this repo: http://github.com/MycroftAI/documentation/

**Comment by fermulator** [comment] 2020-07-03 12:48
Ah yes, confirmed @krisgesling ; I was too eager in the response validation ...

If I do it more carefully:
```
 uninstall count                                                                                                                                                       
 >> Confirming: Shall I remove count by andlo.                                                                                                                         
```

```
 13:46:06.323 | INFO     |   638 | QuestionsAnswersSkill | Searching for remove count skill
Removing event fallback-query.mycroftai:QuestionQueryTimeout
Removing event fallback-query.mycroftai:QuestionQueryTimeout
Removing event fallback-query.mycroftai:QuestionQueryTimeout
Removing event fallback-query.mycroftai:QuestionQueryTimeout
 13:46:07.073 | INFO     |   638 | QuestionsAnswersSkill | Timeout occured check responses
 13:46:12.551 | INFO     |   638 | msm.mycroft_skills_manager | Best match (1.0): count by andlo
```

then
```
Playing WAVE '/home/pi/mycroft-core/mycroft/res/snd/start_listening.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
 13:46:15.857 | INFO     |   644 | __main__:handle_record_begin:37 | Begin Recording...
```

and we type
```
 yes                                                                                                                                                          --- 16.95
 >> count has been removed                                                                                                                                             
```

logs final
```
 13:46:16.597 | INFO     |   638 | msm.skill_entry | Successfully removed count
 13:46:16.598 | INFO     |   638 | msm.mycroft_skills_manager | invalidating skills cache
 13:46:16.643 | INFO     |   638 | mycroft.skills.skill_manager:_unload_removed_skills:322 | removing count.andlo
 13:46:16.676 | INFO     |   638 | mycroft.skills.skill_loader:_execute_instance_shutdown:146 | Skill count.andlo shut down successfully
 13:46:16.677 | INFO     |   638 | msm.mycroft_skills_manager | invalidating skills cache
 13:46:16.680 | INFO     |   638 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
 13:46:18.877 | INFO     |   644 | __main__:handle_record_end:45 | End Recording...
 13:46:20.729 | ERROR    |   644 | mycroft.client.speech.listener:transcribe:239 | list index out of range
 13:46:20.735 | ERROR    |   644 | mycroft.client.speech.listener:transcribe:240 | Speech Recognition could not understand audio
```

(whoops some errors there at the end tho)
