### ISSUE TITLE
UnicodeDecodeError in setup

### ISSUE THREAD

**Issue by burne251** [MycroftAI/mycroft-core#2637] opened 2020-07-15 04:25 UTC
Hi,
I'm trying to set up Mycroft on an Ubuntu 18.0.4 Docker container that I've got some other stuff in, but am running into an issue when I try to run "start_mycroft.sh". I've followed the installation instructions in the README but run into this error:
Already up to date.
Starting all mycroft-core services
Initializing...
Changing ownership of /opt/mycroft to user: with group: root
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting background service audio
Starting background service voice
Starting background service enclosure
Starting cli
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/mycroft/mycroft/__init__.py", line 17, in <module>
    from mycroft.api import Api
  File "/opt/mycroft/mycroft/api/__init__.py", line 22, in <module>
    from mycroft.configuration import Configuration
  File "/opt/mycroft/mycroft/configuration/__init__.py", line 15, in <module>
    from .config import Configuration, LocalConf, RemoteConf
  File "/opt/mycroft/mycroft/configuration/config.py", line 23, in <module>
    from mycroft.util.json_helper import load_commented_json, merge_dict
  File "/opt/mycroft/mycroft/util/__init__.py", line 35, in <module>
    from .parse import extract_datetime, extract_number, normalize
  File "/opt/mycroft/mycroft/util/parse.py", line 32, in <module>
    import lingua_franca.parse
  File "/usr/local/lib/python3.6/dist-packages/lingua_franca/parse.py", line 21, in <module>
    from lingua_franca.lang.parse_pt import *
  File "/usr/local/lib/python3.6/dist-packages/lingua_franca/lang/parse_pt.py", line 200, in <module>
    class PortugueseNormalizer(Normalizer):
  File "/usr/local/lib/python3.6/dist-packages/lingua_franca/lang/parse_pt.py", line 202, in PortugueseNormalizer
    _default_config = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 602: ordinal not in range(128)

I've run dev_setup.sh and such, so not really sure what I'm doing wrong. I'm aware of the docker container available, I'm trying to rig one up myself though. Let me know if I missed anything!

**Comment by forslund** [comment] 2020-07-15 05:55
Hi, sounds a bit like the docker container doesn't have a unicode locale set.

Do you have a [section setting up the locale](https://github.com/MycroftAI/docker-mycroft/blob/master/Dockerfile#L31) in your Dockerfile?

**Comment by burne251** [comment] 2020-07-17 23:20
I was basing my dockerfile on a tensorflow docker image, as I was planning on toying around with DeepSpeech, and had set up my locale, so not sure why it was fussing... I ended up just starting from scratch based on a debian image, and it's working this time. Thanks!

**Comment by forslund** [comment] 2020-07-18 07:26
Great to hear. A bit weird that it didn't work despite the locale being setup :/

**Comment by Mrgove10** [comment] 2021-04-22 19:25
Hi, I get this error too when doing a local Install

**Comment by forslund** [comment] 2021-04-22 19:53
Hi @Mrgove10 it would be interesting to hear what OS you are running and what the output of running `locale` in a terminal is

**Comment by Mrgove10** [comment] 2021-04-22 20:05
There you go @forslund 

System : 
`Linux idefix 4.19.62-sunxi #5.92 SMP Wed Jul 31 22:07:23 CEST 2019 armv7l armv7l armv7l GNU/Linux`

local output : 
```
*LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

dev_setup.py output : 
```
adrien@idefix:~/mycroft-core$ ./dev_setup.sh
Installing packages...
 Installing packages for Debian/Ubuntu/Mint...
[sudo] password for adrien:
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.15.1-3ubuntu2).
bison is already the newest version (2:3.0.4.dfsg-1build1).
build-essential is already the newest version (12.4ubuntu1).
libffi-dev is already the newest version (3.2.1-8).
libjpeg-dev is already the newest version (8c-2ubuntu8).
libtool is already the newest version (2.4.6-2).
pkg-config is already the newest version (0.29.1-0ubuntu2).
python3-setuptools is already the newest version (39.0.1-2).
flac is already the newest version (1.3.2-1).
jq is already the newest version (1.5+dfsg-2).
libfann-dev is already the newest version (2.2.0+ds-3).
mpg123 is already the newest version (1.25.10-1).
portaudio19-dev is already the newest version (19.6.0-1).
swig is already the newest version (3.0.12-1).
curl is already the newest version (7.58.0-2ubuntu3.13).
git is already the newest version (1:2.17.1-1ubuntu0.8).
libglib2.0-dev is already the newest version (2.56.4-0ubuntu0.18.04.8).
libicu-dev is already the newest version (60.2-3ubuntu3.1).
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.9).
pulseaudio is already the newest version (1:11.1-1ubuntu7.11).
pulseaudio-utils is already the newest version (1:11.1-1ubuntu7.11).
screen is already the newest version (4.6.2-1ubuntu1.1).
python3 is already the newest version (3.6.7-1~18.04).
python3-dev is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1882k  100 1882k    0     0  19319      0  0:01:39  0:01:39 --:--:-- 22562
Collecting pip==20.0.2
  Using cached pip-20.0.2-py2.py3-none-any.whl (1.4 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.0.2
WARNING: You are using pip version 20.0.2; however, version 21.0.1 is available.
You should consider upgrading via the '/home/adrien/mycroft-core/.venv/bin/python -m pip install --upgrade pip' command.
grep: ./.git/hooks/pre-commit: No such file or directory
Collecting requests==2.20.0
  Using cached requests-2.20.0-py2.py3-none-any.whl (60 kB)
Collecting gTTS<2.3.0,>=2.2.2
  Using cached gTTS-2.2.2-py3-none-any.whl (25 kB)
Collecting PyAudio==0.2.11
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Collecting pyee==8.1.0
  Using cached pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting SpeechRecognition==3.8.1
  Using cached SpeechRecognition-3.8.1-py2.py3-none-any.whl (32.8 MB)
Collecting tornado==6.0.3
  Using cached tornado-6.0.3.tar.gz (482 kB)
Collecting websocket-client==0.54.0
  Using cached websocket_client-0.54.0-py2.py3-none-any.whl (200 kB)
Collecting requests-futures==0.9.5
  Using cached requests-futures-0.9.5.tar.gz (5.3 kB)
Collecting pyserial==3.0
  Using cached pyserial-3.0.tar.gz (133 kB)
Collecting psutil==5.6.6
  Using cached psutil-5.6.6.tar.gz (447 kB)
Collecting pocketsphinx==0.1.0
  Using cached pocketsphinx-0.1.0.tar.gz (503 kB)
Collecting inflection==0.3.1
  Using cached inflection-0.3.1.tar.gz (8.7 kB)
Collecting pillow==7.1.2
  Using cached Pillow-7.1.2.tar.gz (38.9 MB)
Collecting python-dateutil==2.6.0
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl (194 kB)
Collecting fasteners==0.14.1
  Using cached fasteners-0.14.1-py2.py3-none-any.whl (20 kB)
Collecting PyYAML==5.1.2
  Using cached PyYAML-5.1.2.tar.gz (265 kB)
Collecting lingua-franca==0.2.2
  Using cached lingua_franca-0.2.2-py3-none-any.whl (283 kB)
Collecting msm==0.8.8
  Using cached msm-0.8.8-py3-none-any.whl (25 kB)
Collecting msk==0.3.16
  Using cached msk-0.3.16-py3-none-any.whl (47 kB)
Collecting adapt-parser==0.3.7
  Using cached adapt-parser-0.3.7.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/adrien/mycroft-core/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4co_rrgc/adapt-parser/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4co_rrgc/adapt-parser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4co_rrgc/adapt-parser/pip-egg-info
         cwd: /tmp/pip-install-4co_rrgc/adapt-parser/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4co_rrgc/adapt-parser/setup.py", line 21, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1825: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 21.0.1 is available.
You should consider upgrading via the '/home/adrien/mycroft-core/.venv/bin/python -m pip install --upgrade pip' command.
Warning: Failed to install required dependencies. Continue? y/N
```

**Comment by forslund** [comment] 2021-04-22 21:03
Thanks for the additional info. The locale looks good. the dev-setup.sh sets the C.UTF-8 locale to use a standard locale for the script environment. Can you also check if that locale is installed? `locale -a | grep C.UTF-8`

This was done in response to an issue in docker-mycroft: https://github.com/MycroftAI/docker-mycroft/issues/71 which seems to be similar to your error.

**Comment by Mrgove10** [comment] 2021-04-22 21:10
$ locale -a | grep C.UTF-8
returns : 
C.UTF-8

**Comment by Mrgove10** [comment] 2021-04-22 21:13
I clones the master branch today, so should be on the latest version

**Comment by forslund** [comment] 2021-04-25 12:50
Then the locale should be supported :/ Not quite sure what is going on.

As an experiment could you try to set locale to `en_US.utf8` on [dev_setup.sh#L19](https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh#L19)

**Comment by Mrgove10** [comment] 2021-04-25 13:01
Will do ASAP !

**Comment by Mrgove10** [comment] 2021-04-25 13:58
Tried changing it to `en_US.utf8` Nothing changed i still get the error

Output of locale :
```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
``` 
When i do `locale -a | grep en_US.utf8` i do get the output `en_US.utf8`

**Comment by forslund** [comment] 2021-04-25 16:33
I'm a bit stumped here...could the locale setup be incomplete somehow?

What os is it? `Linux idefix` didn't get me any good answers on google...

Does it work when not trying to enforce the locale:
```
cd tmp
python3 -m venv venv
source venv/bin/activate
pip install adapt-parser
```

**Comment by Mrgove10** [comment] 2021-04-25 16:37
idefix is the machine name

here is the complete os info :
```
$ neofetch
            .-/+oossssoo+/-.               adrien@idefix
        `:+ssssssssssssssssss+:`           -------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.5 LTS armv7l
    .ossssssssssssssssssdMMMNysssso.       Host: Libre Computer Board ALL-H3-CC H3
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.19.62-sunxi
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 days, 6 hours, 17 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1234
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.20
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/0
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Allwinner sun8i Family (4) @ 1.008GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Memory: 421MiB / 967MiB
+sssshhhyNMMNyssssssssssssyNMMMysssssss+
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
Seams to install with no issues when folowing your commands : 
```bash
$ pip install adapt-parser
Collecting adapt-parser
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/f6/38/54bc1a3e23f18678030efc1a98134de1d10323ce1f619d6a1e341db10399/adapt_parser-0.4.0-py3-none-any.whl
Collecting six>=1.10.0 (from adapt-parser)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyee==8.1.0 (from adapt-parser)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/0d/0a/933b3931107e1da186963fd9bb9bceb9a613cff034cb0fb3b0c61003f357/pyee-8.1.0-py2.py3-none-any.whl
Installing collected packages: six, pyee, adapt-parser
Successfully installed adapt-parser-0.4.0 pyee-8.1.0 six-1.15.0
```

**Comment by forslund** [comment] 2021-04-25 16:41
So then if the line in the dev_setup.sh is removed completely, does that work?

**Comment by Mrgove10** [comment] 2021-04-25 16:44
Commented out https://github.com/MycroftAI/mycroft-core/blob/1ba9eda09720b6417661fb68faa776fe4b398d1c/dev_setup.sh#L19 And the error is still there :/

**Comment by Mrgove10** [comment] 2021-04-25 16:45
Just so you can confirm, this is what i did : 
```bash
$ git clone https://github.com/MycroftAI/mycroft-core/
$ git checkout master
$ ./dev_setup.sh
```

**Comment by forslund** [comment] 2021-04-25 16:56
Thanks. Super weird will try to reproduce somehow...

In the meantime you might be able to work around the issue by running

`./dev_setup.sh`
let it fail, then run

```
source .venv/bin/activate
pip install -r requirements/requirements.txt
```
To manually install the python requirements and then try to run 

`./dev_setup.sh`

again. with any luck pip should detect that adapt is at the latest version and skip the install of it.

Another possibility is if you're connecting via SSH the system you're on may be overriding the locale settings causing issues.

**Comment by Mrgove10** [comment] 2021-04-25 17:12
```
$ ./dev_setup.sh
** let it fail **
$ source .venv/bin/activate
$ pip install -r requirements/requirements.txt
** install failed :( **
** open a new console**
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install adapt-parser
$ pip install -r requirements/requirements.txt
** install failed :( **
```
I'm very sorry i'm making you 'loose' time on this :/

**Comment by forslund** [comment] 2021-04-26 04:46
No worries, I'd be interesting to find out what the issue is :)

Btw, do you mean that the `pip install -r requirements/requirements.txt` fails?

**Comment by Mrgove10** [comment] 2021-04-26 06:23
It falls with the same error as before.

**Comment by Mrgove10** [comment] 2021-04-28 16:45
Hi, got some good news.
I remote desktop onto my machine and relauched everything, and it all worked immediately !
Was a little slow to install everything but everything installed !

I think you should have a little warning so that people install it using a Desktop interface, not the CLI.

**Comment by forslund** [comment] 2021-04-28 18:32
Glad you got around the issue. I am curious anyway, I have run the install dozens of times from the CLI without issue so it should (TM) work.

But good to know that a remote desktop is a workaround if the issue appears. maybe we can faq it somehow :) Thanks for figuring this out and sharing the solution!

**Comment by krisgesling** [comment] 2021-04-29 01:29
Just to make sure I'm understanding correctly:
- You're host machine is running Ubuntu 18.04
- You are running Mycroft in a Docker container (also Ubuntu 18.04)
- attempting to install within that running Docker container you got the UnicodeDecodeError
- you used some remote desktop service (VNC? RDP? TeamViewer? Other?) to access your host machine (or the Docker container?)
- it then installed fine.

I think an FAQ / troubleshooting option would be the best option

**Comment by Mrgove10** [comment] 2021-04-29 08:33
No.
I was trying to install on a SBC to be specific, the tritium from libre computer (https://libre.computer/products/boards/all-h3-cc/). I did not use docker at all.
When attempting to install on the machine (while using SSH) i got the error. I then used RDP to connect to it and then it installed fine while on the RDP.

**Comment by krisgesling** [comment] 2021-05-03 08:28
Sorry I merged your responses with the OP in my read of it. 

I've added an item to the general troubleshooting docs page. 

PS cool looking board, would love to hear how it goes via the [Community Forums](https://community.mycroft.ai/).

**Closed by krisgesling** 2021-05-03 08:28 UTC
